import type { Question } from '../types/content'

/**
 * Extra ronde: nieuwe invalshoeken/detailkennis per onderwerp, met parallelle,
 * even-plausibele afleiders (niet uit de optievorm te raden). Origineel
 * materiaal; antwoordsleutels volgen uit de lesstof. Juiste antwoord staat op
 * index 0; de engine husselt de opties bij het examen.
 */
export const examenoefening6Vragen: Record<string, Question[]> = {
  // ───────────── A · Algemeen ─────────────
  'A.1': [
    { id: 'A.1.n1', toetstermCode: 'A.1.1', type: 'mc',
      prompt: 'Welke partij neemt doorgaans het initiatief tot een bouwproject en draagt de financiële verantwoordelijkheid?',
      options: ['De opdrachtgever', 'De constructeur', 'De hoofdaannemer', 'De gemeente'],
      correctIndex: 0,
      explanation: 'De opdrachtgever start het project en betaalt. De architect ontwerpt, de aannemer bouwt, de gemeente vergunt.' },
    { id: 'A.1.n2', toetstermCode: 'A.1.2', type: 'mc',
      prompt: 'Bij de oplevering wordt een document opgesteld met de restpunten die de aannemer nog moet herstellen. Hoe heet dat?',
      options: ['Het proces-verbaal van oplevering', 'Het bestek', 'Het programma van eisen', 'De revisietekening'],
      correctIndex: 0,
      explanation: 'Het proces-verbaal van oplevering legt de opleverpunten vast die nog hersteld moeten worden.' },
    { id: 'A.1.n3', toetstermCode: 'A.1.1', type: 'mc',
      prompt: 'Wie voert in opdracht van de hoofdaannemer een gespecialiseerd deelwerk uit, zoals het stukwerk of de installaties?',
      options: ['De onderaannemer', 'De directievoerder', 'De opdrachtgever', 'De architect'],
      correctIndex: 0,
      explanation: 'De onderaannemer voert een deelwerk uit in opdracht van de hoofdaannemer.' },
    { id: 'A.1.n4', toetstermCode: 'A.1.4', type: 'mc',
      prompt: 'Wat is een "stelpost" in een begroting?',
      options: ['Een gereserveerd bedrag voor een nog niet exact bepaald onderdeel', 'De winstmarge van de aannemer', 'De prijs van het bouwterrein', 'De hypotheekrente'],
      correctIndex: 0,
      explanation: 'Een stelpost is een geraamd bedrag voor een onderdeel dat nog niet definitief is gekozen of geprijsd.' },
  ],
  'A.2.1': [
    { id: 'A.2.1.n1', toetstermCode: 'A.2.1.1', type: 'mc',
      prompt: 'Welke tekening toont een verticale doorgesneden weergave van het gebouw met verdiepingshoogtes?',
      options: ['De doorsnede', 'De plattegrond', 'Het gevelaanzicht', 'De situatietekening'],
      correctIndex: 0,
      explanation: 'De doorsnede is een verticale snede; de plattegrond is een horizontale snede op ± 1 m hoogte.' },
    { id: 'A.2.1.n2', toetstermCode: 'A.2.1.2', type: 'mc',
      prompt: 'Wat legt een revisietekening vast?',
      options: ['De werkelijk uitgevoerde situatie (zoals gebouwd)', 'Het eerste schetsontwerp', 'De aanbestedingsstukken', 'Het programma van eisen'],
      correctIndex: 0,
      explanation: 'Een revisietekening geeft de as-built situatie weer, inclusief wijzigingen die tijdens de bouw zijn doorgevoerd.' },
    { id: 'A.2.1.n3', toetstermCode: 'A.2.1.6', type: 'mc',
      prompt: 'Het bestek bestaat uit twee hoofddelen. Welke?',
      options: ['Een administratief en een technisch deel', 'Een grafisch en een financieel deel', 'Een juridisch en een fiscaal deel', 'Een ontwerp- en een sloopdeel'],
      correctIndex: 0,
      explanation: 'Een bestek heeft een administratief deel (voorwaarden, o.a. UAV) en een technisch deel (werkomschrijving per onderdeel).' },
    { id: 'A.2.1.n4', toetstermCode: 'A.2.1.1', type: 'mc',
      prompt: 'Wat geeft een stramien (stramienlijn) op een bouwtekening aan?',
      options: ['Een systeemlijn (assenstelsel) waarop constructiedelen worden geplaatst', 'De grens van het perceel', 'De noordrichting', 'De hoogte van het maaiveld'],
      correctIndex: 0,
      explanation: 'Stramienlijnen vormen het assenraster waarop kolommen, wanden en fundering worden gepositioneerd en gemaatvoerd.' },
  ],
  'A.2.2': [
    { id: 'A.2.2.n1', toetstermCode: 'A.2.2.4', type: 'mc',
      prompt: 'Welke stroming staat bekend om ambachtelijk baksteenwerk in een soberder, traditionele vorm en werd vaak toegepast bij overheidsgebouwen (jaren 20–50)?',
      options: ['De Delftse School', 'Het Functionalisme', 'De Amsterdamse School', 'Hightech-architectuur'],
      correctIndex: 0,
      explanation: 'De Delftse School is traditioneel en sober in baksteen; de Amsterdamse School is juist uitbundig-expressief.' },
    { id: 'A.2.2.n2', toetstermCode: 'A.2.2.4', type: 'mc',
      prompt: 'Welke stijl toont bewust de constructie en installaties aan de buitenzijde (bv. Centre Pompidou)?',
      options: ['Hightech-architectuur', 'De Jugendstil', 'De Chaletstijl', 'De Delftse School'],
      correctIndex: 0,
      explanation: 'Hightech-architectuur stelt techniek, staal en installaties expliciet tentoon aan de buitenkant.' },
    { id: 'A.2.2.n3', toetstermCode: 'A.2.2.3', type: 'mc',
      prompt: 'Een woning met machinale baksteen, brede kunststof kozijnen en dikke spouwisolatie stamt het meest waarschijnlijk uit:',
      options: ['Na circa 1985', 'Rond 1900', 'De jaren 30', 'Vóór 1850'],
      correctIndex: 0,
      explanation: 'Kunststof kozijnen en (dikke) spouwisolatie wijzen op recente(re) bouw, ruwweg vanaf de jaren 80/90.' },
    { id: 'A.2.2.n4', toetstermCode: 'A.2.2.4', type: 'mc',
      prompt: 'Welke stroming kenmerkt zich door herkenbare, "gebruiksvriendelijke" ruimtelijke structuren waarin de mens centraal staat (bv. Centraal Beheer, Hertzberger)?',
      options: ['Het Structuralisme', 'Het Brutalisme', 'De Nieuwe Zakelijkheid', 'De Amsterdamse School'],
      correctIndex: 0,
      explanation: 'Het structuralisme werkt met herhaalbare, menselijke ruimtelijke eenheden en herkenbare structuren.' },
  ],
  'A.3': [
    { id: 'A.3.n1', toetstermCode: 'A.3.6', type: 'mc',
      prompt: 'Onder welke gevolgklasse van de Wkb valt een complex gebouw met veel publiek, zoals een ziekenhuis of stadion?',
      options: ['Gevolgklasse 3', 'Gevolgklasse 1', 'Gevolgklasse 0', 'Gevolgklasse 2'],
      correctIndex: 0,
      explanation: 'Hoe groter de gevolgen bij falen, hoe hoger de klasse. Ziekenhuizen/stadions vallen in de hoogste klasse (3).' },
    { id: 'A.3.n2', toetstermCode: 'A.3.3', type: 'mc',
      prompt: 'Waar toetst de gemeente bij een aanvraag hoofdzakelijk aan onder de Omgevingswet?',
      options: ['Het omgevingsplan (ruimtelijke regels)', 'De NEN 2767-conditie', 'Het energielabel', 'De UAV 2012'],
      correctIndex: 0,
      explanation: 'De ruimtelijke toets gebeurt aan het omgevingsplan; de bouwtechnische kant loopt (Wkb) via de kwaliteitsborger.' },
    { id: 'A.3.n3', toetstermCode: 'A.3.4', type: 'mc',
      prompt: 'Bij verkoop van bouwgrond is een bodemonderzoek gedaan. Waar dient dat vooral voor?',
      options: ['Vaststellen of de grond verontreinigd is en geschikt voor de beoogde functie', 'Het energielabel bepalen', 'De draagkracht van de fundering berekenen', 'De WOZ-waarde vaststellen'],
      correctIndex: 0,
      explanation: 'Een milieukundig bodemonderzoek beoordeelt verontreiniging en geschiktheid; draagkracht is een apart grondmechanisch onderzoek.' },
    { id: 'A.3.n4', toetstermCode: 'A.3.2', type: 'mc',
      prompt: 'Welke oppervlaktemaat wordt in commercieel vastgoed gebruikt en sluit technische en verticale verkeersruimten uit?',
      options: ['Het verhuurbaar vloeroppervlak (VVO)', 'De gebruiksoppervlakte (GBO)', 'De bruto vloeroppervlakte (BVO)', 'De kadastrale oppervlakte'],
      correctIndex: 0,
      explanation: 'VVO is de commerciële (verhuur)maat, exclusief technische ruimten en verticaal verkeer. GBO/BVO zijn andere maten.' },
  ],

  // ───────────── B · Constructieve opbouw ─────────────
  'B.2': [
    { id: 'B.2.n1', toetstermCode: 'B.2.1', type: 'mc',
      prompt: 'Welke elementengroep bevindt zich (deels) onder het maaiveld en vangt hemelwater/vocht op bij een souterrain?',
      options: ['De kelder', 'Het dak', 'De afwerking', 'De installaties'],
      correctIndex: 0,
      explanation: 'De kelder is de (deels) ondergrondse elementengroep; die moet waterdicht en vochtwerend zijn.' },
    { id: 'B.2.n2', toetstermCode: 'B.2.1', type: 'multi',
      prompt: 'Welke onderdelen horen bij de elementengroep "dak"? (meerdere juist)',
      options: ['De dakbedekking', 'De dakconstructie (sporen/gordingen/spanten)', 'De begane-grondvloer', 'De groepenkast'],
      correctIndices: [0, 1],
      explanation: 'Dakbedekking en dakconstructie vormen het dak. De begane-grondvloer hoort bij de opbouw, de groepenkast bij de installaties.' },
    { id: 'B.2.n3', toetstermCode: 'B.2.1', type: 'mc',
      prompt: 'Waarom denkt een bouwkundige in "elementengroepen"?',
      options: ['Om het gebouw systematisch te kunnen ontwerpen, begroten en beoordelen', 'Om de architectuurstijl te bepalen', 'Om de verkoopprijs te berekenen', 'Om het energielabel af te geven'],
      correctIndex: 0,
      explanation: 'Elementengroepen geven een systematische structuur voor ontwerp, kostenraming en inspectie.' },
  ],
  'B.3': [
    { id: 'B.3.n1', toetstermCode: 'B.3.1', type: 'mc',
      prompt: 'Welke kracht ontstaat als twee delen van een constructie langs elkaar willen verschuiven?',
      options: ['Afschuiving', 'Trek', 'Druk', 'Torsie'],
      correctIndex: 0,
      explanation: 'Langs elkaar verschuivende vlakken geven afschuifkrachten. Torsie is wringing om een as.' },
    { id: 'B.3.n2', toetstermCode: 'B.3.3', type: 'mc',
      prompt: 'Wat is de functie van een windverband in een (staal)constructie?',
      options: ['De constructie stabiel houden tegen horizontale (wind)krachten', 'De vloer dragen', 'De gevel isoleren', 'Het dak waterdicht maken'],
      correctIndex: 0,
      explanation: 'Windverbanden (schoren/diagonalen) nemen horizontale krachten op en zorgen voor stabiliteit.' },
    { id: 'B.3.n3', toetstermCode: 'B.3.2', type: 'mc',
      prompt: 'Waarom kan een driehoek (vakwerk) een stabiele constructievorm vormen?',
      options: ['Een driehoek is vormvast: de hoeken kunnen niet vervormen zonder de staaflengte te wijzigen', 'Een driehoek is het lichtst', 'Een driehoek isoleert het best', 'Een driehoek is altijd het goedkoopst'],
      correctIndex: 0,
      explanation: 'Een driehoek is geometrisch vormvast; daarom zijn vakwerken (opgebouwd uit driehoeken) stabiel en sterk.' },
    { id: 'B.3.n4', toetstermCode: 'B.3.1', type: 'mc',
      prompt: 'Een trekstaaf (bijvoorbeeld in een vakwerk) neemt vooral op:',
      options: ['Trekkrachten', 'Drukkrachten', 'Buiging', 'Torsie'],
      correctIndex: 0,
      explanation: 'Een trekstaaf wordt op trek belast; drukstaven (schoren) juist op druk.' },
  ],
  'B.4': [
    { id: 'B.4.n1', toetstermCode: 'B.4.3', type: 'mc',
      prompt: 'Wat is het resultaat van een boring bij grondonderzoek?',
      options: ['Een boorstaat met de opeenvolgende grondlagen', 'Een sondeerdiagram met weerstand', 'Een energielabel', 'Een kadastrale kaart'],
      correctIndex: 0,
      explanation: 'Een boring levert een boorstaat (laagopbouw). Een sondering geeft een sondeerdiagram met weerstand.' },
    { id: 'B.4.n2', toetstermCode: 'B.4.5', type: 'mc',
      prompt: 'Bij een fundering op staal met losse punten onder kolommen spreek je van:',
      options: ['Poeren', 'Stroken', 'Een funderingsplaat', 'Heipalen'],
      correctIndex: 0,
      explanation: 'Losse funderingsblokken onder kolommen zijn poeren; doorlopende stroken zitten onder wanden.' },
    { id: 'B.4.n3', toetstermCode: 'B.4.2', type: 'mc',
      prompt: 'Welke ondergrond komt vooral in het oosten/zuiden van Nederland voor en draagt over het algemeen goed?',
      options: ['Zand', 'Veen', 'Zeeklei', 'Slappe rivierklei'],
      correctIndex: 0,
      explanation: 'Hoog Nederland (oost/zuid) heeft veel zand: goed draagkrachtig. West-NL heeft slappe klei en veen.' },
    { id: 'B.4.n4', toetstermCode: 'B.4.1', type: 'mc',
      prompt: 'Wat betekent het als grond "zettingsgevoelig" is?',
      options: ['De grond wordt onder belasting in de loop van de tijd samengedrukt', 'De grond geleidt goed warmte', 'De grond is waterdicht', 'De grond is radioactief'],
      correctIndex: 0,
      explanation: 'Zettingsgevoelige grond (veen, klei) drukt onder belasting langzaam in, wat verzakking kan geven.' },
  ],
  'B.5': [
    { id: 'B.5.n1', toetstermCode: 'B.5.3', type: 'mc',
      prompt: 'Uit welk materiaal wordt het binnenblad van een moderne spouwmuur vaak gemaakt vanwege de draagkracht?',
      options: ['Kalkzandsteen of beton', 'Snelbouwbaksteen als sierwerk', 'Cellenbeton als gevelsteen', 'Natuursteen'],
      correctIndex: 0,
      explanation: 'Het dragende binnenblad is vaak kalkzandsteen of beton; het buitenblad is metselwerk (zicht/weer).' },
    { id: 'B.5.n2', toetstermCode: 'B.5.3', type: 'mc',
      prompt: 'Welk licht, goed isolerend maar minder druksterk steenmateriaal wordt gebruikt voor binnenwanden?',
      options: ['Cellenbeton (gasbeton)', 'Graniet', 'Hardsteen', 'Klinkers'],
      correctIndex: 0,
      explanation: 'Cellenbeton (gasbeton) is licht en isolerend, geschikt voor niet-dragende binnenwanden; niet voor zwaar belaste muren.' },
    { id: 'B.5.n3', toetstermCode: 'B.5.10', type: 'mc',
      prompt: 'Witte, poederige uitslag op nieuw metselwerk die na regen verschijnt, heet:',
      options: ['Uitbloei (kalk-/zoutuitslag)', 'Betonrot', 'Craquelé', 'Houtrot'],
      correctIndex: 0,
      explanation: 'Uitbloei is zout/kalk dat naar het oppervlak wordt gevoerd; meestal esthetisch en tijdelijk, geen constructief gebrek.' },
    { id: 'B.5.n4', toetstermCode: 'B.5.7', type: 'mc',
      prompt: 'Boven een deuropening ligt een stalen hoekprofiel dat het metselwerk draagt en tegelijk het buitenblad ophangt. Dit heet een:',
      options: ['Geveldrager', 'Rollaag', 'Latei van hout', 'Muurplaat'],
      correctIndex: 0,
      explanation: 'Een geveldrager (stalen hoeklijn) draagt het buitenblad boven een opening. Een rollaag is gemetseld (meestal siermatig).' },
  ],
  'B.6': [
    { id: 'B.6.n1', toetstermCode: 'B.6.5', type: 'mc',
      prompt: 'Welke prefab-vloer bestaat uit brede elementen met langsholtes en wordt veel als verdiepingsvloer gebruikt?',
      options: ['De kanaalplaatvloer', 'De houten balklaag', 'De gietvloer', 'De cementdekvloer'],
      correctIndex: 0,
      explanation: 'De kanaalplaatvloer (holle kanalen) is licht en overspant groot; standaard prefab verdiepingsvloer.' },
    { id: 'B.6.n2', toetstermCode: 'B.6.5', type: 'mc',
      prompt: 'Bij een breedplaatvloer wordt een dunne prefab plaat op de bouw afgestort met beton. Wat is het voordeel?',
      options: ['De prefab plaat werkt als verloren bekisting én meewerkende onderzijde', 'De vloer hoeft niet gewapend te worden', 'Er is geen kraan nodig', 'De vloer is volledig van hout'],
      correctIndex: 0,
      explanation: 'De breedplaat dient als bekisting en werkt constructief mee met de ter plaatse gestorte druklaag.' },
    { id: 'B.6.n3', toetstermCode: 'B.6.2', type: 'mc',
      prompt: 'Wat is voorgespannen beton?',
      options: ['Beton waarin de wapening vooraf op spanning is gebracht, zodat het minder scheurt en grotere overspanningen aankan', 'Beton dat extra snel uithardt', 'Beton zonder wapening', 'Beton met een gekleurde toplaag'],
      correctIndex: 0,
      explanation: 'Bij voorspanning staan de strengen onder trek; het beton komt onder druk te staan, wat scheurvorming beperkt en grote overspanningen mogelijk maakt.' },
    { id: 'B.6.n4', toetstermCode: 'B.6.1', type: 'mc',
      prompt: 'Waarmee wordt de verwerkbaarheid (consistentie) van vers beton vaak gecontroleerd?',
      options: ['Met de zetmaat (kegel van Abrams)', 'Met een sondeerconus', 'Met een vochtmeter', 'Met een waterpas'],
      correctIndex: 0,
      explanation: 'De zetmaatproef (kegel van Abrams) meet hoe ver vers beton inzakt: een maat voor de verwerkbaarheid.' },
  ],
  'B.7': [
    { id: 'B.7.n1', toetstermCode: 'B.7.2', type: 'mc',
      prompt: 'Wat is het verschil tussen een HEA- en een HEB-profiel van dezelfde hoogte?',
      options: ['Het HEB-profiel is zwaarder/dikker en draagt meer', 'Het HEA-profiel is altijd van RVS', 'Het HEB-profiel is U-vormig', 'Er is geen verschil'],
      correctIndex: 0,
      explanation: 'Bij gelijke hoogte is de HEB zwaarder (dikkere flenzen/lijf) en sterker dan de lichtere HEA.' },
    { id: 'B.7.n2', toetstermCode: 'B.7.4', type: 'mc',
      prompt: 'Een verbinding die krachten én momenten overbrengt (de hoek blijft stijf) noem je:',
      options: ['Een momentvaste verbinding', 'Een scharnierende verbinding', 'Een glijdende oplegging', 'Een roloplegging'],
      correctIndex: 0,
      explanation: 'Een momentvaste (stijve) verbinding houdt de hoek vast en draagt ook buigende momenten over; een scharnier doet dat niet.' },
    { id: 'B.7.n3', toetstermCode: 'B.7.2', type: 'mc',
      prompt: 'Welk stalen profiel is een gesloten vierkant of rechthoekig buisprofiel, gunstig tegen wringing (torsie)?',
      options: ['Een koker', 'Een IPE-profiel', 'Een UNP-profiel', 'Een L-profiel'],
      correctIndex: 0,
      explanation: 'Een gesloten koker is torsiestijf. Open profielen (IPE, UNP, L) zijn juist gevoeliger voor wringing.' },
    { id: 'B.7.n4', toetstermCode: 'B.7.4', type: 'mc',
      prompt: 'Welke lasvorm verbindt twee platen die haaks op elkaar staan met een driehoekige lasnaad in de hoek?',
      options: ['Een hoeklas', 'Een stompe las', 'Een klinknagel', 'Een boutverbinding'],
      correctIndex: 0,
      explanation: 'Een hoeklas legt een driehoekige naad in de hoek tussen twee delen; een stompe las verbindt delen in elkaars verlengde.' },
  ],
  'B.8': [
    { id: 'B.8.n1', toetstermCode: 'B.8.2', type: 'mc',
      prompt: 'Waarom moet je aluminium en koper niet in direct, vochtig contact met elkaar toepassen?',
      options: ['Er ontstaat galvanische corrosie (het onedeler metaal tast aan)', 'Ze smelten samen', 'Ze worden radioactief', 'Ze isoleren dan niet meer'],
      correctIndex: 0,
      explanation: 'Twee verschillende metalen vormen met vocht een galvanisch element; het onedeler metaal (aluminium) corrodeert versneld.' },
    { id: 'B.8.n2', toetstermCode: 'B.8.1', type: 'mc',
      prompt: 'Welk metaal wordt gebruikt als dakbedekking met felsnaden en is relatief licht?',
      options: ['Zink', 'Lood', 'Gietijzer', 'Brons'],
      correctIndex: 0,
      explanation: 'Zink wordt met felsnaden als lichte dakbedekking toegepast. Lood is zwaar en voor detaillering/loketten.' },
    { id: 'B.8.n3', toetstermCode: 'B.8.4', type: 'mc',
      prompt: 'Brons is een legering van vooral:',
      options: ['Koper en tin', 'Koper en zink', 'IJzer en chroom', 'Aluminium en silicium'],
      correctIndex: 0,
      explanation: 'Brons = koper + tin. Messing = koper + zink.' },
    { id: 'B.8.n4', toetstermCode: 'B.8.1', type: 'mc',
      prompt: 'Waarom worden non-ferro metalen (zink, koper, lood, aluminium) juist voor dakwerk en detaillering gebruikt?',
      options: ['Ze roesten niet zoals ijzer en zijn goed vervormbaar/waterdicht', 'Ze zijn brandbaar', 'Ze zijn radioactief', 'Ze geleiden geen water'],
      correctIndex: 0,
      explanation: 'Non-ferro metalen bevatten geen ijzer en roesten niet; ze zijn goed vervormbaar en weerbestendig.' },
  ],
  'B.9': [
    { id: 'B.9.n1', toetstermCode: 'B.9.5', type: 'mc',
      prompt: 'Welke houtverbinding wordt gemaakt door een pen in een uitgehakt gat te steken (klassieke kozijn-/houtskeletverbinding)?',
      options: ['Pen-en-gatverbinding', 'Zwaluwstaartverbinding', 'Vingerlas', 'Messing-en-groef'],
      correctIndex: 0,
      explanation: 'De pen-en-gatverbinding is de klassieke haakse houtverbinding (o.a. in kozijnen).' },
    { id: 'B.9.n2', toetstermCode: 'B.9.7', type: 'mc',
      prompt: 'Wat is "verduurzaamd" hout in bouwkundige zin?',
      options: ['Hout dat behandeld is om het beter tegen vocht en aantasting te beschermen', 'Hout van een bedreigde boomsoort', 'Hout dat CO₂ uitstoot', 'Hout dat alleen binnen mag'],
      correctIndex: 0,
      explanation: 'Verduurzaamd hout is behandeld (bv. geïmpregneerd of thermisch gemodificeerd) tegen vocht, schimmel en insecten.' },
    { id: 'B.9.n3', toetstermCode: 'B.9.2', type: 'mc',
      prompt: 'Kleine ronde gaatjes met boormeel in oud houtwerk wijzen meestal op:',
      options: ['Houtworm/kevers (insectenaantasting)', 'Optrekkend vocht', 'Een koudebrug', 'Normale krimp'],
      correctIndex: 0,
      explanation: 'Ronde uitvlieggaatjes met boormeel duiden op insectenaantasting (houtworm/boktor). Rot is juist zacht/brokkelig.' },
    { id: 'B.9.n4', toetstermCode: 'B.9.4', type: 'mc',
      prompt: 'Welk plaatmateriaal bestaat uit grote, gerichte houtspanen in lagen en wordt veel voor beplating/dakbeschot gebruikt?',
      options: ['OSB', 'MDF', 'Multiplex', 'Hardboard'],
      correctIndex: 0,
      explanation: 'OSB (Oriented Strand Board) heeft grote, gerichte spanen; MDF is fijn vezelmateriaal, multiplex is fineer.' },
  ],
  'B.10': [
    { id: 'B.10.n1', toetstermCode: 'B.10.2', type: 'mc',
      prompt: 'Welk raam kan zowel draaien (om een verticale as) als kiepen (bovenaan open)?',
      options: ['Het draaikiepraam', 'Het schuifraam', 'Het valraam', 'Het tuimelraam'],
      correctIndex: 0,
      explanation: 'Een draaikiepraam kent twee standen: draaien voor volledige opening en kiepen voor ventilatie.' },
    { id: 'B.10.n2', toetstermCode: 'B.10.4', type: 'mc',
      prompt: 'Wat is een pui in een gevel?',
      options: ['Een samengesteld kozijn met ramen en/of deuren als geheel', 'Een dragende betonbalk', 'Een dakdoorvoer', 'Een isolatieplaat'],
      correctIndex: 0,
      explanation: 'Een pui is een groter, samengesteld kozijn (bv. met deur en zijlichten) dat de gevelopening invult.' },
    { id: 'B.10.n3', toetstermCode: 'B.10.4', type: 'mc',
      prompt: 'Welke afdichting hoort bij "droog" beglazen?',
      options: ['Rubberprofielen (beglazingsrubbers)', 'Stopverf/kit', 'Cementmortel', 'Purschuim'],
      correctIndex: 0,
      explanation: 'Droog beglazen gebruikt rubberprofielen; nat beglazen gebruikt kit/stopverf.' },
    { id: 'B.10.n4', toetstermCode: 'B.10.6', type: 'mc',
      prompt: 'Een deur die naar je toe opengaat met de scharnieren rechts, is:',
      options: ['Een rechtsdraaiende deur', 'Een linksdraaiende deur', 'Een taatsdeur', 'Een schuifdeur'],
      correctIndex: 0,
      explanation: 'De draairichting wordt bepaald aan de zijde waar de deur naartoe opent; scharnieren rechts = rechtsdraaiend (volgens de gangbare afspraak).' },
  ],
  'B.12': [
    { id: 'B.12.n1', toetstermCode: 'B.12.1', type: 'mc',
      prompt: 'Hoe heet de zware balk waarop de lichtere vloerbalken (kinderbinten) rusten?',
      options: ['De moerbalk', 'De raveelbalk', 'De strijkbalk', 'De nokbalk'],
      correctIndex: 0,
      explanation: 'De moerbalk is de zware draagbalk; de kinderbinten rusten erop. Een raveelbalk zit rond een sparing.' },
    { id: 'B.12.n2', toetstermCode: 'B.12.4', type: 'mc',
      prompt: 'Waarom is een goede thermische schil rondom vloeren en wanden belangrijk voor comfort?',
      options: ['Om warmteverlies en koude oppervlakken (met condens/schimmel) te voorkomen', 'Om de woning zwaarder te maken', 'Om geluid te versterken', 'Om meer daglicht te krijgen'],
      correctIndex: 0,
      explanation: 'Een sluitende isolatieschil beperkt warmteverlies en koude oppervlakken, wat condens en schimmel voorkomt.' },
    { id: 'B.12.n3', toetstermCode: 'B.12.1', type: 'mc',
      prompt: 'Waarmee wordt een verlaagd plafond meestal opgebouwd?',
      options: ['Een regelwerk met beplating (bv. gipsplaat)', 'Massief beton ter plaatse gestort', 'Een spouwmuur', 'Dakpannen'],
      correctIndex: 0,
      explanation: 'Een verlaagd plafond is een licht regelwerk met beplating, o.a. om leidingen weg te werken en te isoleren.' },
  ],
  'B.13': [
    { id: 'B.13.n1', toetstermCode: 'B.13.1', type: 'mc',
      prompt: 'Een kap waarvan de nok evenwijdig aan de straat loopt, noem je een:',
      options: ['Langskap', 'Dwarskap', 'Kruiskap', 'Tentdak'],
      correctIndex: 0,
      explanation: 'Bij een langskap ligt de nok evenwijdig aan de straat/voorgevel; bij een dwarskap staat de nok er haaks op.' },
    { id: 'B.13.n2', toetstermCode: 'B.13.5', type: 'mc',
      prompt: 'Welke platdak-bedekking is een rubberachtig, in grote banen leverbaar materiaal met een lange levensduur?',
      options: ['EPDM', 'Keramische pannen', 'Leien', 'Riet'],
      correctIndex: 0,
      explanation: 'EPDM is een rubberfolie voor platte daken, in grote banen met weinig naden en een lange levensduur.' },
    { id: 'B.13.n3', toetstermCode: 'B.13.5', type: 'mc',
      prompt: 'Dunne, splijtbare grijze natuursteenplaatjes als dakbedekking heten:',
      options: ['Leien', 'Pannen', 'Shingles', 'Golfplaten'],
      correctIndex: 0,
      explanation: 'Leien zijn dunne (natuur- of kunst)steenplaatjes, in overlappende rijen gelegd.' },
    { id: 'B.13.n4', toetstermCode: 'B.13.2', type: 'mc',
      prompt: 'Waar dienen tengels en panlatten onder de dakpannen voor?',
      options: ['Ventilatie/afwatering onder de pannen én het ophangen van de pannen', 'Het isoleren van het dak', 'Het dragen van de nok alleen', 'Het afwerken van de gevel'],
      correctIndex: 0,
      explanation: 'Tengels zorgen voor een luchtspouw/afwatering op het folie; op de panlatten haken de pannen.' },
  ],
  'B.14': [
    { id: 'B.14.n1', toetstermCode: 'B.14.2', type: 'mc',
      prompt: 'Wat is de "boom" van een trap?',
      options: ['De schuine zijbalk waarin/waarop de treden bevestigd zijn', 'De bovenste trede', 'De handleuning', 'Het bordes'],
      correctIndex: 0,
      explanation: 'De trapbomen zijn de schuine zijdelen die de treden dragen. De leuning is de handgreep.' },
    { id: 'B.14.n2', toetstermCode: 'B.14.6', type: 'mc',
      prompt: 'Voor rolstoeltoegankelijkheid wordt in plaats van een trap vaak toegepast:',
      options: ['Een hellingbaan met een flauwe helling', 'Een spiltrap', 'Een vlizotrap', 'Een steile steektrap'],
      correctIndex: 0,
      explanation: 'Een flauwe hellingbaan maakt een hoogteverschil overbrugbaar voor rolstoelen; trappen zijn dat niet.' },
    { id: 'B.14.n3', toetstermCode: 'B.14.5', type: 'mc',
      prompt: 'Wat is de functie van het tegengewicht bij een tractielift?',
      options: ['Het balanceert de kooi zodat de motor minder vermogen hoeft te leveren', 'Het remt de lift bij stroomuitval', 'Het verwarmt de schacht', 'Het verlicht de kooi'],
      correctIndex: 0,
      explanation: 'Het tegengewicht compenseert het gewicht van de kooi, zodat de aandrijving alleen het verschil hoeft te bewegen.' },
    { id: 'B.14.n4', toetstermCode: 'B.14.1', type: 'mc',
      prompt: 'Een inklapbare zoldertrap die je vanuit een luik naar beneden trekt, is een:',
      options: ['Vlizotrap', 'Bordestrap', 'Wenteltrap', 'Kwartslagtrap'],
      correctIndex: 0,
      explanation: 'Een vlizotrap is een opvouwbare zoldertrap in een dakluik; niet bedoeld voor dagelijks intensief gebruik.' },
  ],
  'B.15': [
    { id: 'B.15.n1', toetstermCode: 'B.15.1', type: 'mc',
      prompt: 'Welke kunststof is taai en slijtvast en wordt o.a. voor waterleiding, touw en meubelscharnieren gebruikt?',
      options: ['Polypropeen (PP)', 'Perspex (PMMA)', 'Polycarbonaat (PC)', 'EPS'],
      correctIndex: 0,
      explanation: 'PP is taai, slijtvast en chemisch bestendig; PMMA/PC zijn juist doorzichtige plaatmaterialen.' },
    { id: 'B.15.n2', toetstermCode: 'B.15.1', type: 'mc',
      prompt: 'Waarvoor wordt polyetheen (PE)-folie op de bouw veel gebruikt?',
      options: ['Als dampremmende/waterkerende folie en bouwfolie', 'Als dragend constructiedeel', 'Als brandwerende plaat', 'Als isolatieschuim'],
      correctIndex: 0,
      explanation: 'PE-folie is goedkoop, waterdicht en flexibel; veel toegepast als bouw-/dampremmende folie.' },
    { id: 'B.15.n3', toetstermCode: 'B.15.1', type: 'mc',
      prompt: 'Een thermohardende kunststof, versterkt met glasvezel (GVK/polyester), wordt gebruikt voor:',
      options: ['Lichtdoorlatende golfplaten, boten en dakkoepels', 'Rioolbuizen', 'Isolatieschuim in de spouw', 'Dampremmende folie'],
      correctIndex: 0,
      explanation: 'Glasvezelversterkt polyester (thermohard) is sterk en vormvast; toegepast in panelen, koepels en boten.' },
  ],
  'B.16': [
    { id: 'B.16.n1', toetstermCode: 'B.16.1', type: 'mc',
      prompt: 'Welk isolatiemateriaal is gemaakt van cellulair glas, volledig waterdicht en drukvast (o.a. onder fundering)?',
      options: ['Foamglas', 'Glaswol', 'EPS', 'Vlas'],
      correctIndex: 0,
      explanation: 'Foamglas (cellulair glas) neemt geen water op en is drukvast; geschikt op zwaar belaste, vochtige plekken.' },
    { id: 'B.16.n2', toetstermCode: 'B.16.1', type: 'mc',
      prompt: 'Waarom draagt goede isolatie bij aan comfort én aan een lager energieverbruik?',
      options: ['Minder warmteverlies: minder stoken en warmere oppervlakken binnen', 'Isolatie verwarmt zelf de woning', 'Isolatie maakt de woning zwaarder', 'Isolatie vervangt de ventilatie'],
      correctIndex: 0,
      explanation: 'Isolatie beperkt warmteverlies; daardoor is minder verwarming nodig en voelen wanden minder koud aan.' },
    { id: 'B.16.n3', toetstermCode: 'B.16.1', type: 'mc',
      prompt: 'Bij het na-isoleren van een dak van binnenuit is een dampremmende laag aan de warme zijde belangrijk om:',
      options: ['Inwendige condensatie in de isolatie/constructie te voorkomen', 'De isolatie te dragen', 'Geluid te weren', 'De dakpannen vast te zetten'],
      correctIndex: 0,
      explanation: 'De dampremmer aan de warme zijde houdt vochtige binnenlucht tegen, zodat er geen condens in de constructie ontstaat.' },
  ],

  // ───────────── C · Afwerking en installaties ─────────────
  'C.1': [
    { id: 'C.1.n1', toetstermCode: 'C.1.4', type: 'mc',
      prompt: 'Waarvoor dient de ontspanningsleiding (beluchting) die vanaf de standleiding naar het dak loopt?',
      options: ['Drukverschillen opheffen zodat sifons niet leeggezogen worden', 'Regenwater afvoeren', 'Warm water leveren', 'Gas afvoeren'],
      correctIndex: 0,
      explanation: 'De ontspanningsleiding belucht het riool, zodat onderdruk de watersloten (sifons) niet wegzuigt.' },
    { id: 'C.1.n2', toetstermCode: 'C.1.3', type: 'mc',
      prompt: 'In het buitengebied zonder riool wordt afvalwater soms lokaal gezuiverd met een:',
      options: ['IBA (Individuele Behandeling van Afvalwater) of septic tank', 'Hydrofoor', 'Warmtepomp', 'Expansievat'],
      correctIndex: 0,
      explanation: 'Zonder rioolaansluiting zuivert een IBA of septic tank het afvalwater lokaal.' },
    { id: 'C.1.n3', toetstermCode: 'C.1.1', type: 'mc',
      prompt: 'Een greppel/laagte die regenwater vasthoudt en laat infiltreren in de bodem heet een:',
      options: ['Wadi', 'Beerput', 'Standleiding', 'Sifon'],
      correctIndex: 0,
      explanation: 'Een wadi bergt en infiltreert hemelwater; goed bij een gescheiden stelsel en klimaatadaptatie.' },
    { id: 'C.1.n4', toetstermCode: 'C.1.7', type: 'mc',
      prompt: 'Welk sanitair toestel loost het meeste (en meest vervuilde) afvalwater en heeft een grote afvoer nodig?',
      options: ['Het closet (wc)', 'De wastafel', 'De doucheput', 'De fontein'],
      correctIndex: 0,
      explanation: 'Het closet loost fecaliën en heeft een ruime afvoer met stankafsluiter nodig.' },
  ],
  'C.2': [
    { id: 'C.2.n1', toetstermCode: 'C.2.2', type: 'mc',
      prompt: 'Welk toestel verwarmt water pas op het moment dat je de kraan opent (geen voorraad)?',
      options: ['Een doorstroomtoestel (geiser/combiketel-tapdeel)', 'Een voorraadboiler', 'Een expansievat', 'Een hydrofoor'],
      correctIndex: 0,
      explanation: 'Een doorstroomtoestel verwarmt water direct bij afname; een boiler houdt een voorraad warm.' },
    { id: 'C.2.n2', toetstermCode: 'C.2.1', type: 'mc',
      prompt: 'Wat is de functie van een expansievat in een cv- of warmwatersysteem?',
      options: ['De volumetoename van opwarmend water opvangen zodat de druk niet te hoog wordt', 'De waterdruk verhogen', 'Legionella doden', 'Het water onthard maken'],
      correctIndex: 0,
      explanation: 'Water zet uit bij verwarming; het expansievat vangt die volumetoename op en houdt de systeemdruk in de hand.' },
    { id: 'C.2.n3', toetstermCode: 'C.2.5', type: 'mc',
      prompt: 'Wat doet een wateronthardingsinstallatie?',
      options: ['Kalk (hardheid) uit het water halen om kalkaanslag te beperken', 'De waterdruk verhogen', 'Het water verwarmen', 'Legionella met UV doden'],
      correctIndex: 0,
      explanation: 'Een waterontharder verlaagt de hardheid (kalk), wat kalkaanslag in leidingen en toestellen vermindert.' },
    { id: 'C.2.n4', toetstermCode: 'C.2.7', type: 'mc',
      prompt: 'Waarom is een dode (niet-gebruikte) leidingaftakking een legionella-risico?',
      options: ['Er staat lauw water lang stil, ideaal voor bacteriegroei', 'Er ontstaat te hoge druk', 'Het water wordt te koud', 'De leiding roest sneller'],
      correctIndex: 0,
      explanation: 'In dode leidingen staat lauw water stil; dat bevordert legionella. Vermijd dode einden en spoel regelmatig.' },
  ],
  'C.4': [
    { id: 'C.4.n1', toetstermCode: 'C.4.1', type: 'mc',
      prompt: 'Wat is krachtstroom?',
      options: ['Een driefasenaansluiting (400 V) voor zware apparaten', 'Extra beveiligde 230 V voor de badkamer', 'Gelijkstroom van zonnepanelen', 'Noodstroom uit een accu'],
      correctIndex: 0,
      explanation: 'Krachtstroom is een 3-fasenaansluiting (400 V) voor zware apparatuur (bv. inductiekookplaat, machines).' },
    { id: 'C.4.n2', toetstermCode: 'C.4.2', type: 'mc',
      prompt: 'Waarom worden badkamer en buitenaansluitingen op een aardlekschakelaar met hoge gevoeligheid (30 mA) aangesloten?',
      options: ['Vanwege het hogere risico op elektrocutie in natte omgevingen', 'Omdat daar meer stroom nodig is', 'Om energie te besparen', 'Om de kabels dunner te kunnen maken'],
      correctIndex: 0,
      explanation: 'In natte ruimten is elektrocutiegevaar groter; een gevoelige aardlekschakelaar (30 mA) schakelt snel uit.' },
    { id: 'C.4.n3', toetstermCode: 'C.4.2', type: 'mc',
      prompt: 'Waarvoor dient het verdelen van een installatie over meerdere groepen?',
      options: ['Om de belasting te spreiden en bij een storing niet de hele woning uit te schakelen', 'Om de energierekening te verhogen', 'Om meer gas te gebruiken', 'Om de waterdruk te regelen'],
      correctIndex: 0,
      explanation: 'Meerdere groepen spreiden de belasting en zorgen dat een storing/uitval beperkt blijft tot één groep.' },
  ],
  'C.5': [
    { id: 'C.5.n1', toetstermCode: 'C.5.1', type: 'mc',
      prompt: 'Wat is het voordeel van power-optimizers of micro-omvormers per paneel?',
      options: ['Schaduw op één paneel drukt de opbrengst van de andere panelen minder', 'De panelen worden zwaarder', 'Er is geen omvormer meer nodig', 'De panelen leveren wisselstroom af zonder omzetting'],
      correctIndex: 0,
      explanation: 'Per-paneel-optimalisatie beperkt het opbrengstverlies door schaduw of vervuiling op een enkel paneel.' },
    { id: 'C.5.n2', toetstermCode: 'C.5.3', type: 'mc',
      prompt: 'Een zonneboiler heeft naast de collector meestal ook nodig:',
      options: ['Een voorraadvat en een naverwarmer voor als de zon onvoldoende levert', 'Een omvormer', 'Een groepenkast met krachtstroom', 'Een expansievat voor gas'],
      correctIndex: 0,
      explanation: 'Een zonneboiler slaat warm water op in een voorraadvat en heeft een naverwarming (bv. cv-ketel) voor donkere dagen.' },
    { id: 'C.5.n3', toetstermCode: 'C.5.2', type: 'mc',
      prompt: 'Waarvan hangt de daadwerkelijke jaaropbrengst van zonnepanelen sterk af?',
      options: ['Oriëntatie, hellingshoek, schaduw en het weer', 'Alleen het merk van de omvormer', 'De kleur van het dak', 'Het bouwjaar van de woning'],
      correctIndex: 0,
      explanation: 'Naast het paneelvermogen bepalen ligging (zuid/hoek), schaduw en weersomstandigheden de opbrengst.' },
  ],
  'C.6': [
    { id: 'C.6.n1', toetstermCode: 'C.6.1', type: 'mc',
      prompt: 'Wat is een warmtenet (stadsverwarming)?',
      options: ['Een collectief net dat warmte (warm water) van een centrale bron naar woningen levert', 'Een net van elektrische kabels', 'Een gasleidingnet', 'Een rioolstelsel'],
      correctIndex: 0,
      explanation: 'Een warmtenet distribueert warmte via warm water vanuit een centrale bron (restwarmte, geothermie) naar aangesloten gebouwen.' },
    { id: 'C.6.n2', toetstermCode: 'C.6.3', type: 'mc',
      prompt: 'Wat regelt een weersafhankelijke (buitenvoeler-)regeling op de cv?',
      options: ['De aanvoertemperatuur afstemmen op de buitentemperatuur voor comfort en zuinigheid', 'De waterdruk verhogen', 'De ventilatie sturen', 'Het gasverbruik meten'],
      correctIndex: 0,
      explanation: 'Een weersafhankelijke regeling verlaagt de aanvoertemperatuur bij zachter weer, wat comfort en rendement verbetert.' },
    { id: 'C.6.n3', toetstermCode: 'C.6.9', type: 'mc',
      prompt: 'Wat is een voordeel van vloerverwarming ten opzichte van radiatoren?',
      options: ['Gelijkmatige warmte bij lage temperatuur, geschikt voor een warmtepomp', 'Snellere opwarming van de ruimte', 'Geen enkele installatie nodig', 'Meer stof en tocht'],
      correctIndex: 0,
      explanation: 'Vloerverwarming geeft gelijkmatige stralingswarmte bij lage temperatuur (LTV), ideaal met een warmtepomp; ze warmt wel trager op.' },
    { id: 'C.6.n4', toetstermCode: 'C.6.6', type: 'mc',
      prompt: 'Via welk medium transporteert een cv-installatie de warmte door de woning?',
      options: ['Water (in leidingen naar radiatoren/vloer)', 'Gas', 'Lucht via kanalen', 'Elektriciteit door de vloer'],
      correctIndex: 0,
      explanation: 'Een cv gebruikt water als transportmedium naar radiatoren of vloerverwarming. Luchtverwarming gebruikt lucht.' },
  ],
  'C.8': [
    { id: 'C.8.n1', toetstermCode: 'C.8.2', type: 'mc',
      prompt: 'Welk blusmiddel is het meest geschikt voor een beginnende brand in elektrische apparatuur?',
      options: ['Een koolzuursneeuw (CO₂)-blusser', 'Een emmer water', 'Een schuimblusser met veel water', 'Een natte doek'],
      correctIndex: 0,
      explanation: 'CO₂ blust zonder residu en zonder geleiding — geschikt bij elektra. Water geleidt en is gevaarlijk bij spanning.' },
    { id: 'C.8.n2', toetstermCode: 'C.8.4', type: 'mc',
      prompt: 'Wat doet een brandmeldinstallatie (BMI) met doormelding (OMS)?',
      options: ['Automatisch de brandweer alarmeren bij detectie', 'De sprinkler vullen met water', 'De vluchtwegen verlichten', 'De lift naar boven sturen'],
      correctIndex: 0,
      explanation: 'Een BMI detecteert brand; via een OMS wordt de melding automatisch doorgezet naar de brandweer.' },
    { id: 'C.8.n3', toetstermCode: 'C.8.5', type: 'mc',
      prompt: 'Wat is de functie van een zelfsluitende brandwerende deur in een gang?',
      options: ['De verspreiding van brand en rook tussen compartimenten beperken', 'De gang verwarmen', 'De akoestiek verbeteren', 'Daglicht toelaten'],
      correctIndex: 0,
      explanation: 'Een zelfsluitende brandwerende deur houdt brand/rook tegen tussen compartimenten en moet daarom dicht (kunnen) vallen.' },
    { id: 'C.8.n4', toetstermCode: 'C.8.3', type: 'mc',
      prompt: 'Wat detecteert een koolmonoxidemelder (in tegenstelling tot een rookmelder)?',
      options: ['Het giftige, reukloze gas CO uit onvolledige verbranding', 'Rookdeeltjes', 'Warmte', 'Waterdamp'],
      correctIndex: 0,
      explanation: 'Een CO-melder detecteert koolmonoxide (reukloos, giftig) uit onvolledige verbranding; een rookmelder detecteert rook.' },
  ],
  'C.9': [
    { id: 'C.9.n1', toetstermCode: 'C.9.4', type: 'mc',
      prompt: 'Waarom stelt het Bbl minimum-eisen aan ventilatiecapaciteit in woningen?',
      options: ['Om vocht, CO₂ en vervuilde binnenlucht af te voeren voor een gezond binnenklimaat', 'Om de woning te verwarmen', 'Om geluid te weren', 'Om inbraak te voorkomen'],
      correctIndex: 0,
      explanation: 'Voldoende ventilatie voert vocht, CO₂ en verontreiniging af; te weinig ventilatie geeft schimmel en een ongezond klimaat.' },
    { id: 'C.9.n2', toetstermCode: 'C.9.2', type: 'mc',
      prompt: 'Wat is een nadeel van gebalanceerde ventilatie (systeem D) bij slecht onderhoud?',
      options: ['Vervuilde filters/kanalen verminderen luchtkwaliteit en rendement', 'Het systeem gaat vanzelf harder verwarmen', 'Er ontstaat overdruk in het gasnet', 'De woning wordt te vochtig door regen'],
      correctIndex: 0,
      explanation: 'Systeem D vraagt onderhoud (filters, kanaalreiniging); bij verwaarlozing daalt de luchtkwaliteit en het WTW-rendement.' },
    { id: 'C.9.n3', toetstermCode: 'C.9.5', type: 'mc',
      prompt: 'Waarom is afzuiging boven het kookvuur belangrijk?',
      options: ['Om vocht, vet en verbrandingsproducten direct bij de bron af te voeren', 'Om de keuken te verwarmen', 'Om de pannen sneller warm te maken', 'Om geluid te dempen'],
      correctIndex: 0,
      explanation: 'Kookafzuiging voert vocht, vet en (bij gas) verbrandingsproducten af bij de bron, wat het binnenklimaat gezond houdt.' },
  ],
  'C.11': [
    { id: 'C.11.n1', toetstermCode: 'C.11.1', type: 'mc',
      prompt: 'Welk glas heeft een licht getinte/gebobbelde structuur en wordt bij monumenten toegepast om de oude uitstraling te behouden?',
      options: ['Monumentenglas (getrokken glas)', 'HR++-glas', 'Draadglas', 'Gehard glas'],
      correctIndex: 0,
      explanation: 'Monumentenglas (getrokken/mondgeblazen) heeft lichte oneffenheden en past bij historische panden.' },
    { id: 'C.11.n2', toetstermCode: 'C.11.2', type: 'mc',
      prompt: 'Waardoor isoleert HR++-glas beter dan gewoon dubbelglas?',
      options: ['Een onzichtbare metaalcoating én edelgas (argon) in de spouw', 'Dikkere glasbladen alleen', 'Een grotere luchtspouw met gewone lucht', 'Een gekleurde folie'],
      correctIndex: 0,
      explanation: 'De low-e-coating weerkaatst warmtestraling en het edelgas beperkt geleiding; samen geeft dat een lage U-waarde.' },
    { id: 'C.11.n3', toetstermCode: 'C.11.3', type: 'mc',
      prompt: 'Wat is het verschil tussen "nat" en "droog" beglazen?',
      options: ['Nat = met kit/stopverf; droog = met rubberprofielen', 'Nat = in de regen; droog = bij droog weer', 'Nat = enkel glas; droog = dubbel glas', 'Er is geen verschil'],
      correctIndex: 0,
      explanation: 'Nat beglazen dicht af met kit/stopverf; droog beglazen gebruikt beglazingsrubbers.' },
  ],
  'C.12': [
    { id: 'C.12.n1', toetstermCode: 'C.12.1', type: 'mc',
      prompt: 'Welk deel van een slot schiet uit zodra je de deur dichttrekt en houdt hem dicht zonder te sluiten met de sleutel?',
      options: ['De dagschoot (loopslot)', 'De nachtschoot', 'De cilinder', 'De sluitkom'],
      correctIndex: 0,
      explanation: 'De schuine dagschoot valt vanzelf in bij het dichttrekken. De nachtschoot vergrendel je extra met de sleutel/knop.' },
    { id: 'C.12.n2', toetstermCode: 'C.12.1', type: 'mc',
      prompt: 'Wat is de functie van een sluitplaat/sluitkom in het kozijn?',
      options: ['De schoten van het slot opvangen en de kracht op het kozijn verdelen', 'Het glas vasthouden', 'De deur laten scharnieren', 'De deur isoleren'],
      correctIndex: 0,
      explanation: 'De sluitkom/sluitplaat vangt de dag- en nachtschoot op en verdeelt inbraakkrachten over het kozijn.' },
    { id: 'C.12.n3', toetstermCode: 'C.12.2', type: 'mc',
      prompt: 'Wat is het doel van het Politiekeurmerk Veilig Wonen op het gebied van hang- en sluitwerk?',
      options: ['Een inbreker minstens een aantal minuten ophouden (met SKG-materiaal)', 'De woning verwarmen', 'De ventilatie verbeteren', 'Het energielabel verhogen'],
      correctIndex: 0,
      explanation: 'PKVW eist inbraakwerend (SKG-)materiaal en maatregelen die de inbreker vertragen en afschrikken.' },
  ],
  'C.13': [
    { id: 'C.13.n1', toetstermCode: 'C.13.3', type: 'mc',
      prompt: 'Blaasvorming en afbladderen van buitenverf ontstaat vaak doordat:',
      options: ['Er vocht onder de verflaag zit dat naar buiten wil', 'De verf te dik is opgebracht', 'De ondergrond te glad was', 'De kleur te donker is'],
      correctIndex: 0,
      explanation: 'Vocht onder de verf (bv. door een lek of te nat hout) drukt de laag omhoog: blaasvorming en afbladderen.' },
    { id: 'C.13.n2', toetstermCode: 'C.13.1', type: 'mc',
      prompt: 'Welke wandafwerking bestaat uit rollen bedrukt/gestructureerd papier of vlies dat op de wand wordt gelijmd?',
      options: ['Behang', 'Spachtelputz', 'Tegelwerk', 'Sauswerk'],
      correctIndex: 0,
      explanation: 'Behang wordt als rollen op de wand gelijmd. Spachtelputz is een gespachtelde pleisterstructuur.' },
    { id: 'C.13.n3', toetstermCode: 'C.13.5', type: 'mc',
      prompt: 'Waarom worden wandtegels en vloertegels verschillend gekozen?',
      options: ['Vloertegels moeten sterker, slijtvaster en stroever (antislip) zijn', 'Wandtegels zijn altijd dikker', 'Vloertegels zijn nooit glad', 'Er is geen verschil in eisen'],
      correctIndex: 0,
      explanation: 'Vloertegels dragen belasting en slijtage en moeten stroef zijn; wandtegels zijn lichter en mogen gladder.' },
    { id: 'C.13.n4', toetstermCode: 'C.13.8', type: 'mc',
      prompt: 'Welke vloerafwerking bestaat uit dunne kunststofstroken/-tegels die op de ondervloer worden gelijmd of geklikt?',
      options: ['Pvc-vloer', 'Gietvloer', 'Parketvloer', 'Betonvloer'],
      correctIndex: 0,
      explanation: 'Een pvc-vloer bestaat uit kunststofstroken/-tegels. Een gietvloer is naadloos gegoten; parket is hout.' },
  ],
  'C.14': [
    { id: 'C.14.n1', toetstermCode: 'C.14.1', type: 'mc',
      prompt: 'Tot welke groep behoort zandsteen?',
      options: ['Afzettingsgesteente (sediment)', 'Stollingsgesteente', 'Metamorf gesteente', 'Kunststeen'],
      correctIndex: 0,
      explanation: 'Zandsteen is door bezinking en verkitting ontstaan: afzettingsgesteente. Graniet = stolling, marmer = metamorf.' },
    { id: 'C.14.n2', toetstermCode: 'C.14.2', type: 'mc',
      prompt: 'Waarvoor wordt hardsteen (Belgisch hardsteen) vaak toegepast?',
      options: ['Voor dorpels, traptreden en vensterbanken (slijtvast)', 'Als isolatiemateriaal', 'Als dakbedekking', 'Als dampremmende folie'],
      correctIndex: 0,
      explanation: 'Hardsteen is slijtvast en wordt gebruikt voor dorpels, treden en vensterbanken.' },
    { id: 'C.14.n3', toetstermCode: 'C.14.2', type: 'mc',
      prompt: 'Waarom is marmer minder geschikt voor een buitenaanrecht of zure omgeving?',
      options: ['Marmer is kalkhoudend en wordt door zuren aangetast/dof', 'Marmer smelt in de zon', 'Marmer is brandbaar', 'Marmer geleidt elektriciteit'],
      correctIndex: 0,
      explanation: 'Marmer (metamorfe kalksteen) reageert met zuren en verweert/dooft; graniet is daar veel bestendiger.' },
  ],

  // ───────────── D · Kwaliteit, onderhoud, duurzaamheid ─────────────
  'D.1': [
    { id: 'D.1.n1', toetstermCode: 'D.1.4', type: 'mc',
      prompt: 'Onderhoud dat pas plaatsvindt nádat een gebrek is opgetreden, heet:',
      options: ['Correctief onderhoud', 'Preventief onderhoud', 'Planmatig onderhoud', 'Mutatieonderhoud'],
      correctIndex: 0,
      explanation: 'Correctief onderhoud is herstel achteraf. Preventief/planmatig onderhoud gebeurt juist vooraf om gebreken te voorkomen.' },
    { id: 'D.1.n2', toetstermCode: 'D.1.4', type: 'mc',
      prompt: 'Onderhoud dat een verhuurder uitvoert tussen twee huurders in (bij leegstand) heet:',
      options: ['Mutatieonderhoud', 'Correctief onderhoud', 'Planmatig groot onderhoud', 'Preventief onderhoud'],
      correctIndex: 0,
      explanation: 'Mutatieonderhoud vindt plaats bij wisseling van huurder (mutatie), om de woning weer verhuurklaar te maken.' },
    { id: 'D.1.n3', toetstermCode: 'D.1.6', type: 'mc',
      prompt: 'Wat is de "instandhoudingstermijn" van een bouwdeel?',
      options: ['De verwachte periode dat het onderdeel zonder vervanging functioneert', 'De garantietermijn van de aannemer', 'De afschrijvingstermijn voor de belasting', 'De looptijd van de hypotheek'],
      correctIndex: 0,
      explanation: 'De instandhoudingstermijn is de verwachte levensduur waarin een onderdeel (met onderhoud) blijft functioneren.' },
  ],
  'D.2': [
    { id: 'D.2.n1', toetstermCode: 'D.2.1', type: 'mc',
      prompt: 'Bij het beoordelen van een kozijn steek je met een priem in het onderhout. Waar test je op?',
      options: ['Houtrot (zacht, doorborend hout)', 'De verfkleur', 'De glasdikte', 'De isolatiewaarde'],
      correctIndex: 0,
      explanation: 'Met een priem test je of het hout zacht/rot is; wegzakken duidt op houtrot.' },
    { id: 'D.2.n2', toetstermCode: 'D.2.2', type: 'mc',
      prompt: 'Een scheur die loopt langs de dilatatievoeg (bewegingsvoeg) van een lang gebouw is meestal:',
      options: ['Het gevolg van normale uitzetting/krimp die de voeg juist moet opvangen', 'Een teken van instortingsgevaar', 'Altijd houtrot', 'Een lekkage van de waterleiding'],
      correctIndex: 0,
      explanation: 'Dilatatievoegen vangen bewegingen (uitzetten/krimpen) op; scheuren die daar netjes stoppen zijn meestal geen constructief alarm.' },
    { id: 'D.2.n3', toetstermCode: 'D.2.1', type: 'mc',
      prompt: 'Groene aanslag en vochtplekken laag op een noordgevel duiden vooral op:',
      options: ['Blijvend vocht/weinig zon (algen), meestal esthetisch', 'Een verzakte fundering', 'Betonrot in de gevel', 'Een gaslek'],
      correctIndex: 0,
      explanation: 'Noordgevels drogen traag; algen/vochtplekken zijn meestal esthetisch, geen constructief gebrek.' },
  ],
  'D.3': [
    { id: 'D.3.n1', toetstermCode: 'D.3.4', type: 'mc',
      prompt: 'Wat is oppervlaktecondensatie?',
      options: ['Vocht dat neerslaat op een koud binnenoppervlak (bv. een enkelglas-ruit of koudebrug)', 'Vocht diep in de constructie', 'Optrekkend vocht uit de bodem', 'Regenlekkage door het dak'],
      correctIndex: 0,
      explanation: 'Oppervlaktecondens ontstaat als warme, vochtige lucht een koud oppervlak raakt (enkel glas, koudebrug).' },
    { id: 'D.3.n2', toetstermCode: 'D.3.5', type: 'mc',
      prompt: 'Wat betekent het Bbl met een minimale Rc-eis voor nieuwbouw?',
      options: ['Dat dichte constructies (dak, gevel, vloer) minimaal een bepaalde warmteweerstand moeten hebben', 'Dat het glas een maximale dikte heeft', 'Dat de woning gasloos moet zijn', 'Dat er een minimaal aantal ramen is'],
      correctIndex: 0,
      explanation: 'De Rc-eis stelt een minimale warmteweerstand aan dichte scheidingsconstructies (isolatie-eis).' },
    { id: 'D.3.n3', toetstermCode: 'D.3.10', type: 'mc',
      prompt: 'Waarvan is de hoeveelheid daglicht in een ruimte vooral afhankelijk?',
      options: ['De grootte en plaatsing van de raamopeningen (glasoppervlak)', 'De kleur van de vloer', 'Het aantal stopcontacten', 'De dikte van de fundering'],
      correctIndex: 0,
      explanation: 'Daglichttoetreding hangt vooral af van het glasoppervlak en de oriëntatie/plaatsing van de ramen.' },
    { id: 'D.3.n4', toetstermCode: 'D.3.11', type: 'mc',
      prompt: 'Welke maatregel vermindert vooral contactgeluid tussen verdiepingen?',
      options: ['Een zwevende dekvloer (ontkoppeld van de constructievloer)', 'Dubbel glas in de gevel', 'Een dikkere buitenmuur', 'Meer ventilatie'],
      correctIndex: 0,
      explanation: 'Een zwevende dekvloer ontkoppelt de loopvloer van de draagvloer en dempt zo contactgeluid.' },
  ],
  'D.4': [
    { id: 'D.4.n1', toetstermCode: 'D.4.1', type: 'mc',
      prompt: 'Wat is de kern van de "Trias Energetica"?',
      options: ['Eerst beperken (isoleren), dan duurzame bronnen, dan pas efficiënt fossiel', 'Zoveel mogelijk gas gebruiken', 'Alleen op prijs sturen', 'Eerst zonnepanelen, dan pas isoleren'],
      correctIndex: 0,
      explanation: 'Trias Energetica: 1) beperk de vraag (isoleren), 2) gebruik duurzame energie, 3) gebruik resterend fossiel zo efficiënt mogelijk.' },
    { id: 'D.4.n2', toetstermCode: 'D.4.3', type: 'multi',
      prompt: 'Welke voorzieningen wijzen op een verduurzaamde bestaande woning? (meerdere juist)',
      options: ['Zonnepanelen', 'Een warmtepomp', 'HR++/triple glas', 'Een open gasgeiser'],
      correctIndices: [0, 1, 2],
      explanation: 'Zonnepanelen, warmtepomp en HR++/triple glas duiden op verduurzaming. Een open gasgeiser is juist verouderd.' },
    { id: 'D.4.n3', toetstermCode: 'D.4.5', type: 'mc',
      prompt: 'Wat is een "materialenpaspoort" bij circulair bouwen?',
      options: ['Een register van welke materialen in een gebouw zitten, met het oog op hergebruik', 'Een energielabel', 'Een bouwvergunning', 'Een taxatierapport'],
      correctIndex: 0,
      explanation: 'Een materialenpaspoort legt vast welke materialen/producten in het gebouw zitten, zodat ze later herbruikt kunnen worden.' },
    { id: 'D.4.n4', toetstermCode: 'D.4.7', type: 'mc',
      prompt: 'Wat betekent "bio-based" bouwen?',
      options: ['Bouwen met materialen van hernieuwbare, plantaardige oorsprong (hout, vlas, hennep)', 'Bouwen met uitsluitend beton', 'Bouwen zonder isolatie', 'Bouwen met gerecycled staal alleen'],
      correctIndex: 0,
      explanation: 'Bio-based materialen komen uit hernieuwbare, plantaardige bronnen (hout, vlas, hennep) en leggen vaak CO₂ vast.' },
  ],
}
