import type { Question } from '../types/content'

/**
 * 200 KENNIS-TEST vragen: opgesteld zodat het antwoord niet uit de vorm van de
 * opties te raden is. Alle afleiders zijn even plausibel en parallel
 * geformuleerd (vaak veelgemaakte denkfouten), zodat je echt moet redeneren.
 * De opties worden bovendien door de engine gehusseld. Geen kopieën van de
 * officiële oefenexamens; antwoordsleutels volgen uit de lesstof.
 *
 * Conventie: het juiste antwoord staat hier op index 0; shuffleQuestionOptions
 * verplaatst het bij het examen naar een willekeurige positie.
 */
export const examenoefening5Vragen: Record<string, Question[]> = {
  // ───────────────────────── A · Algemeen ─────────────────────────
  'A.1': [
    {
      id: 'A.1.k1', toetstermCode: 'A.1.1', type: 'mc',
      prompt: 'Wie houdt tijdens de uitvoering namens de opdrachtgever toezicht of conform bestek en tekening wordt gebouwd?',
      options: ['De directievoerder / het toezicht', 'De hoofdaannemer', 'De onderaannemer', 'De materiaalleverancier'],
      correctIndex: 0,
      explanation: 'De directievoerder (toezichthouder) controleert namens de opdrachtgever; de aannemer voert uit en controleert zichzelf niet onafhankelijk.',
    },
    {
      id: 'A.1.k2', toetstermCode: 'A.1.1', type: 'mc',
      prompt: 'Het programma van eisen (PvE) legt in de eerste plaats vast:',
      options: ['De wensen, functies en het budget van de opdrachtgever', 'De constructieberekening van de fundering', 'De planning van de onderaannemers', 'De definitieve verkoopprijs'],
      correctIndex: 0,
      explanation: 'Het PvE beschrijft wat de opdrachtgever wil (functies, ruimten, budget). De architect vertaalt dat naar een ontwerp; de constructeur rekent later.',
    },
    {
      id: 'A.1.k3', toetstermCode: 'A.1.2', type: 'mc',
      prompt: 'Wat gebeurt er in de nazorgfase, direct ná de oplevering?',
      options: ['Herstel van opleveringspunten en afhandeling van garanties', 'Het opstellen van het bestek', 'De aanbesteding van het werk', 'Het maken van het schetsontwerp'],
      correctIndex: 0,
      explanation: 'Na oplevering worden restpunten hersteld en garanties afgehandeld. Bestek, aanbesteding en schetsontwerp horen bij eerdere fases.',
    },
    {
      id: 'A.1.k4', toetstermCode: 'A.1.4', type: 'mc',
      prompt: 'Naast de directe bouwkosten bevat de aanneemsom onder meer:',
      options: ['Algemene kosten, winst en risico', 'De overdrachtsbelasting', 'De hypotheekrente van de koper', 'De courtage van de makelaar'],
      correctIndex: 0,
      explanation: 'De aannemer rekent bovenop de directe kosten algemene kosten (AK) plus winst en risico. Belasting, rente en courtage staan hier los van.',
    },
    {
      id: 'A.1.k5', toetstermCode: 'A.1.3', type: 'mc',
      prompt: 'Wat betekent "bouwrijp maken" van een terrein?',
      options: ['Het terrein ontsluiten, egaliseren/ophogen en van riolering en aansluitingen voorzien', 'De fundering storten', 'De begane-grondvloer leggen', 'Het metselwerk optrekken'],
      correctIndex: 0,
      explanation: 'Bouwrijp maken is het voorbereiden van de grond (ontsluiten, ophogen, riolering/nutsvoorzieningen) vóór de bouw start.',
    },
  ],
  'A.2.1': [
    {
      id: 'A.2.1.k1', toetstermCode: 'A.2.1.1', type: 'mc',
      prompt: 'Op welke schaal wordt een situatietekening doorgaans getekend?',
      options: ['1:1000 of 1:500', '1:100', '1:20', '1:5'],
      correctIndex: 0,
      explanation: 'De situatietekening toont het gebouw in zijn omgeving en staat op een kleine schaal (1:1000/1:500). Plattegronden 1:100, details 1:5/1:10.',
    },
    {
      id: 'A.2.1.k2', toetstermCode: 'A.2.1.1', type: 'mc',
      prompt: 'Op een plattegrond staat de arcering van schuine, evenwijdige strepen. Welk materiaal is dit?',
      options: ['Baksteen (metselwerk)', 'Gewapend beton', 'Isolatie', 'Hout in de lengte'],
      correctIndex: 0,
      explanation: 'Schuine evenwijdige strepen = baksteen. Gewapend beton is stippels + driehoekjes met diagonale lijnen; isolatie heeft een eigen arcering.',
    },
    {
      id: 'A.2.1.k3', toetstermCode: 'A.2.1.2', type: 'mc',
      prompt: 'Een gevelaanzicht op schaal 1:100: een deur is op tekening 21 mm hoog. Hoe hoog is de deur in werkelijkheid?',
      options: ['2,1 m', '0,21 m', '21 m', '1,05 m'],
      correctIndex: 0,
      explanation: 'Bij 1:100 is werkelijkheid = 100× de tekeningmaat: 21 mm × 100 = 2100 mm = 2,1 m (standaard deurhoogte).',
    },
    {
      id: 'A.2.1.k4', toetstermCode: 'A.2.1.1', type: 'mc',
      prompt: 'Wat geeft het peil (P of PP) op een bouwtekening aan?',
      options: ['Het nul-niveau waarvandaan alle hoogtes worden gemeten (meestal de bovenkant begane-grondvloer)', 'De noordrichting', 'De schaal van de tekening', 'De dikte van de fundering'],
      correctIndex: 0,
      explanation: 'Het peil is het hoogte-nulpunt (vaak bovenkant afgewerkte begane-grondvloer); alle + en − maten zijn hierop betrokken.',
    },
    {
      id: 'A.2.1.k5', toetstermCode: 'A.2.1.5', type: 'mc',
      prompt: 'Als bestek en tekening elkaar tegenspreken, wat geldt dan volgens de gangbare regel?',
      options: ['Het bestek gaat vóór de tekening', 'De tekening gaat vóór het bestek', 'De aannemer kiest zelf', 'De laatst gedateerde bijlage wint altijd'],
      correctIndex: 0,
      explanation: 'Bij tegenstrijdigheid gaat het bestek vóór de tekening; in de praktijk overlegt de aannemer dit met de directie.',
    },
  ],
  'A.2.2': [
    {
      id: 'A.2.2.k1', toetstermCode: 'A.2.2.2', type: 'mc',
      prompt: 'Een woning zit aan beide zijden vast aan buren en ligt midden in een rij. Welk type is dit?',
      options: ['Tussenwoning', 'Hoekwoning', 'Twee-onder-een-kapwoning', 'Vrijstaande woning'],
      correctIndex: 0,
      explanation: 'Midden in een rij, met aan beide zijden buren = tussenwoning. Aan het einde van de rij = hoekwoning.',
    },
    {
      id: 'A.2.2.k2', toetstermCode: 'A.2.2.4', type: 'mc',
      prompt: 'Sierlijke, organische lijnen en florale motieven rond 1900 zijn kenmerkend voor welke stroming?',
      options: ['Jugendstil (art nouveau)', 'Functionalisme', 'De Stijl', 'Brutalisme'],
      correctIndex: 0,
      explanation: 'Jugendstil/art nouveau (rond 1900) is sierlijk en organisch. Functionalisme en De Stijl zijn juist strak en geometrisch; brutalisme is ruw beton.',
    },
    {
      id: 'A.2.2.k3', toetstermCode: 'A.2.2.4', type: 'mc',
      prompt: 'Rechthoekige vlakken, primaire kleuren (rood, geel, blauw) en asymmetrie kenmerken:',
      options: ['De Stijl', 'De Amsterdamse School', 'De Chaletstijl', 'De Jugendstil'],
      correctIndex: 0,
      explanation: 'De Stijl (o.a. Rietveld) werkt met abstracte vlakken en primaire kleuren. De Amsterdamse School is expressief baksteenwerk.',
    },
    {
      id: 'A.2.2.k4', toetstermCode: 'A.2.2.3', type: 'mc',
      prompt: 'Vanaf welke periode werd de spouwmuur in Nederlandse woningbouw gangbaar?',
      options: ['Vanaf ongeveer 1920–1930', 'Vanaf ongeveer 1850', 'Pas na 1975', 'Pas na 2000'],
      correctIndex: 0,
      explanation: 'De spouwmuur werd rond 1920–1930 standaard. Woningen van vóór die tijd hebben meestal een massieve (steens) buitenmuur.',
    },
    {
      id: 'A.2.2.k5', toetstermCode: 'A.2.2.8', type: 'mc',
      prompt: 'Wat is typerend voor een "tuindorp" als stedenbouwkundig concept?',
      options: ['Laagbouw met veel groen en tuinen in een dorpse opzet', 'Hoogbouw rond een verkeersplein', 'Uitsluitend kantoren en bedrijven', 'Woningen zonder enige buitenruimte'],
      correctIndex: 0,
      explanation: 'Een tuindorp (bv. Vreewijk) is ruime laagbouw met veel groen en tuinen — een reactie op de dichtbebouwde 19e-eeuwse stad.',
    },
  ],
  'A.3': [
    {
      id: 'A.3.k1', toetstermCode: 'A.3.1', type: 'mc',
      prompt: 'De bouwtechnische eisen (constructie, brand, ventilatie) staan onder de Omgevingswet in:',
      options: ['Het Besluit bouwwerken leefomgeving (Bbl)', 'Het omgevingsplan', 'De Woningwet', 'De UAV 2012'],
      correctIndex: 0,
      explanation: 'Het Bbl bevat de bouwtechnische eisen (opvolger Bouwbesluit). Het omgevingsplan gaat over de ruimtelijke regels van de gemeente.',
    },
    {
      id: 'A.3.k2', toetstermCode: 'A.3.6', type: 'mc',
      prompt: 'Een eenvoudige eengezinswoning valt onder welke gevolgklasse van de Wkb?',
      options: ['Gevolgklasse 1', 'Gevolgklasse 2', 'Gevolgklasse 3', 'Gevolgklasse 4'],
      correctIndex: 0,
      explanation: 'Eenvoudige bouwwerken (grondgebonden woningen, kleine bedrijfsgebouwen) vallen onder gevolgklasse 1, waarmee de Wkb is gestart.',
    },
    {
      id: 'A.3.k3', toetstermCode: 'A.3.2', type: 'mc',
      prompt: 'Welke oppervlaktemaat vermeldt een makelaar volgens NEN 2580 als "woonoppervlak" in de advertentie?',
      options: ['De gebruiksoppervlakte (GBO)', 'De bruto vloeroppervlakte (BVO)', 'De kadastrale perceeloppervlakte', 'De netto-inhoud in m³'],
      correctIndex: 0,
      explanation: 'De GBO (binnenwerks, exclusief muren) is de advertentiemaat. BVO wordt aan de buitenzijde gemeten (inclusief muren).',
    },
    {
      id: 'A.3.k4', toetstermCode: 'A.3.1', type: 'mc',
      prompt: 'Voor welke ingreep is doorgaans wél een omgevingsvergunning nodig?',
      options: ['Het wijzigen van een dragende constructie', 'Het plaatsen van een niet-dragende scheidingswand binnen', 'Het schilderen van de gevel in dezelfde kleur', 'Het vervangen van een kraan'],
      correctIndex: 0,
      explanation: 'Wijzigen van de draagconstructie raakt de veiligheid en is vergunningplichtig. Niet-constructieve, inpandige klussen zijn meestal vergunningsvrij.',
    },
    {
      id: 'A.3.k5', toetstermCode: 'A.3.4', type: 'mc',
      prompt: 'Bij verbouwing van een woning uit 1975 wordt asbestverdacht materiaal aangetroffen. Wat geldt?',
      options: ['Verwijdering moet door een gecertificeerd bedrijf gebeuren na inventarisatie', 'De bewoner mag het zelf zonder maatregelen weghalen', 'Asbest is sinds 1970 verboden en komt niet meer voor', 'Er gelden geen regels voor asbest in woningen'],
      correctIndex: 0,
      explanation: 'Asbest vraagt eerst een inventarisatie en (bij risico) verwijdering door een gecertificeerd bedrijf. Zelf verwijderen mag alleen in beperkte, aangewezen gevallen.',
    },
  ],

  // ─────────────────────── B · Constructieve opbouw ───────────────────────
  'B.1': [
    {
      id: 'B.1.k1', toetstermCode: 'B.1.1', type: 'mc',
      prompt: 'Welke Vitruvius-kwaliteit staat voor bruikbaarheid?',
      options: ['Utilitas', 'Firmitas', 'Venustas', 'Gravitas'],
      correctIndex: 0,
      explanation: 'Utilitas = bruikbaarheid, firmitas = stevigheid, venustas = schoonheid. "Gravitas" hoort niet in de triade.',
    },
    {
      id: 'B.1.k2', toetstermCode: 'B.1.1', type: 'mc',
      prompt: 'De moderne eis "constructieve veiligheid" is de directe voortzetting van welke Vitruvius-kwaliteit?',
      options: ['Firmitas (stevigheid)', 'Utilitas (bruikbaarheid)', 'Venustas (schoonheid)', 'Geen van de drie'],
      correctIndex: 0,
      explanation: 'Firmitas (stevigheid/duurzaamheid) vertaalt zich naar de eis van constructieve veiligheid.',
    },
    {
      id: 'B.1.k3', toetstermCode: 'B.1.1', type: 'mc',
      prompt: 'Welke van de drie kwaliteiten is het meest smaakgevoelig en tijdgebonden?',
      options: ['Venustas (schoonheid)', 'Firmitas (stevigheid)', 'Utilitas (bruikbaarheid)', 'Alle drie evenveel'],
      correctIndex: 0,
      explanation: 'Schoonheid (venustas) is subjectief en verandert met de mode; stevigheid en bruikbaarheid zijn objectiever te toetsen.',
    },
    {
      id: 'B.1.k4', toetstermCode: 'B.1.1', type: 'mc',
      prompt: 'Een woning is fraai en stevig, maar door de indeling nauwelijks te bewonen. Aan welke kwaliteit ontbreekt het?',
      options: ['Utilitas', 'Firmitas', 'Venustas', 'Aan geen enkele'],
      correctIndex: 0,
      explanation: 'Een onbruikbare indeling is een gebrek aan bruikbaarheid (utilitas), ook al zijn schoonheid en stevigheid in orde.',
    },
    {
      id: 'B.1.k5', toetstermCode: 'B.1.1', type: 'mc',
      prompt: 'Welke kwaliteit beoordeel je als makelaar door te kijken naar logische routing, daglicht en afmetingen van ruimten?',
      options: ['Utilitas (bruikbaarheid)', 'Firmitas (stevigheid)', 'Venustas (schoonheid)', 'Geen; dat is niet te beoordelen'],
      correctIndex: 0,
      explanation: 'Routing, daglicht en maatvoering bepalen de bruikbaarheid (utilitas) van een woning.',
    },
  ],
  'B.2': [
    {
      id: 'B.2.k1', toetstermCode: 'B.2.1', type: 'mc',
      prompt: 'Tot welke elementengroep behoort een verdiepingsvloer?',
      options: ['De opbouw (bovengrondse draagstructuur)', 'De fundering', 'Het dak', 'De installaties'],
      correctIndex: 0,
      explanation: 'Verdiepingsvloeren horen bij de opbouw. Fundering, dak en installaties zijn eigen elementengroepen.',
    },
    {
      id: 'B.2.k2', toetstermCode: 'B.2.1', type: 'mc',
      prompt: 'Welke elementengroep zorgt voor de bovenafsluiting van het gebouw tegen weer en wind?',
      options: ['Het dak', 'De fundering', 'De installaties', 'De afwerking'],
      correctIndex: 0,
      explanation: 'Het dak sluit het gebouw bovenaan af tegen regen, wind en warmteverlies.',
    },
    {
      id: 'B.2.k3', toetstermCode: 'B.2.1', type: 'mc',
      prompt: 'De cv-ketel, leidingen en groepenkast horen bij welke elementengroep?',
      options: ['De installaties', 'De opbouw', 'De afwerking', 'Het dak'],
      correctIndex: 0,
      explanation: 'Verwarming, water, gas en elektra vormen samen de elementengroep installaties.',
    },
    {
      id: 'B.2.k4', toetstermCode: 'B.2.1', type: 'mc',
      prompt: 'Wat is de belangrijkste functie van de fundering binnen de hoofdopbouw?',
      options: ['De belastingen overbrengen naar de draagkrachtige ondergrond', 'De woning verwarmen', 'De gevel afwerken', 'Daglicht toelaten'],
      correctIndex: 0,
      explanation: 'De fundering draagt alle belastingen af naar de stevige grondlaag.',
    },
    {
      id: 'B.2.k5', toetstermCode: 'B.2.1', type: 'mc',
      prompt: 'Stucwerk, tegels en vloerbedekking behoren tot welke elementengroep?',
      options: ['De afwerking', 'De opbouw', 'De installaties', 'De fundering'],
      correctIndex: 0,
      explanation: 'Wand-, vloer- en plafondafwerkingen vormen de elementengroep afwerking.',
    },
  ],
  'B.3': [
    {
      id: 'B.3.k1', toetstermCode: 'B.3.1', type: 'mc',
      prompt: 'Onder welke belasting valt sneeuw op een dak?',
      options: ['Variabele (veranderlijke) belasting', 'Permanente belasting', 'Eigen gewicht', 'Reactiekracht'],
      correctIndex: 0,
      explanation: 'Sneeuw is er niet altijd en varieert: variabele belasting. Eigen gewicht van de constructie is permanent.',
    },
    {
      id: 'B.3.k2', toetstermCode: 'B.3.1', type: 'mc',
      prompt: 'Beton is sterk onder druk maar zwak onder trek. In een vrij opgelegde balk zit de trekzone:',
      options: ['Aan de onderzijde', 'Aan de bovenzijde', 'In het hart', 'Overal gelijk'],
      correctIndex: 0,
      explanation: 'Bij een vrij opgelegde, doorbuigende balk rekt de onderzijde uit (trek). Daar komt de trekwapening.',
    },
    {
      id: 'B.3.k3', toetstermCode: 'B.3.2', type: 'mc',
      prompt: 'Hoe noem je een constructiedeel dat aan één zijde is ingeklemd en vrij uitsteekt, zoals een balkon?',
      options: ['Een uitkraging (console)', 'Een overspanning', 'Een oplegging', 'Een trekstang'],
      correctIndex: 0,
      explanation: 'Aan één zijde ingeklemd, vrij uitstekend = uitkraging/console. Een overspanning ligt op twee steunpunten.',
    },
    {
      id: 'B.3.k4', toetstermCode: 'B.3.3', type: 'mc',
      prompt: 'Wat is de "overspanning" van een ligger?',
      options: ['De afstand tussen twee steunpunten', 'De dikte van de ligger', 'De hoogte van de ligger', 'Het gewicht van de ligger'],
      correctIndex: 0,
      explanation: 'De overspanning is de vrije afstand tussen de opleggingen. Grotere overspanning → meer doorbuiging bij gelijke doorsnede.',
    },
    {
      id: 'B.3.k5', toetstermCode: 'B.3.1', type: 'mc',
      prompt: 'Een kolom draagt de last van bovenliggende vloeren. Welke kracht werkt vooral in de kolom?',
      options: ['Druk', 'Trek', 'Afschuiving', 'Torsie'],
      correctIndex: 0,
      explanation: 'Een verticale draagkolom wordt vooral op druk belast door het gewicht dat erboven rust.',
    },
  ],
  'B.4': [
    {
      id: 'B.4.k1', toetstermCode: 'B.4.2', type: 'mc',
      prompt: 'Welke grondsoort draagt het beste en is het minst zettingsgevoelig?',
      options: ['Zand', 'Veen', 'Klei', 'Slappe leem'],
      correctIndex: 0,
      explanation: 'Zand is goed draagkrachtig en weinig samendrukbaar. Veen en klei zijn slap en zettingsgevoelig.',
    },
    {
      id: 'B.4.k2', toetstermCode: 'B.4.5', type: 'mc',
      prompt: 'Wat betekent "fundering op staal"?',
      options: ['Een ondiepe fundering vlak onder het maaiveld', 'Een fundering van stalen platen', 'Een fundering op stalen heipalen', 'Een fundering met stalen damwanden'],
      correctIndex: 0,
      explanation: 'Fundering "op staal" is een ondiepe fundering (stroken/plaat); "staal" verwijst níét naar het materiaal.',
    },
    {
      id: 'B.4.k3', toetstermCode: 'B.4.3', type: 'mc',
      prompt: 'Wat meet je met een sondering (CPT)?',
      options: ['De weerstand/draagkracht van de grond op diepte', 'De exacte grondsamenstelling in laagjes', 'Het grondwaterpeil', 'De marktwaarde van de kavel'],
      correctIndex: 0,
      explanation: 'Een sondering meet de conus- en wrijvingsweerstand (draagkracht). Voor de laagopbouw doe je een boring.',
    },
    {
      id: 'B.4.k4', toetstermCode: 'B.4.6', type: 'mc',
      prompt: 'Houten funderingspalen moeten om aantasting te voorkomen:',
      options: ['Continu onder de grondwaterspiegel blijven', 'Zo droog mogelijk staan', 'Regelmatig geverfd worden', 'Boven het maaiveld uitsteken'],
      correctIndex: 0,
      explanation: 'Houten palen blijven goed onder water; droogstand (lage grondwaterstand) veroorzaakt paalrot.',
    },
    {
      id: 'B.4.k5', toetstermCode: 'B.4.6', type: 'mc',
      prompt: 'Grond die náást een paal wegzakt en aan de paal "trekt", geeft:',
      options: ['Negatieve kleef (extra neerwaartse belasting)', 'Opwaartse druk', 'Minder belasting op de paal', 'Geen enkel effect'],
      correctIndex: 0,
      explanation: 'Meezakkende grond wrijft langs de paal naar beneden: negatieve kleef, een extra last op de paal.',
    },
    {
      id: 'B.4.k6', toetstermCode: 'B.4.9', type: 'mc',
      prompt: 'Waarvoor dient een damwand bij een diepe bouwput?',
      options: ['De omringende grond (en soms water) keren zodat de put niet instort', 'Het gebouw dragen', 'De kelder isoleren', 'Hemelwater afvoeren'],
      correctIndex: 0,
      explanation: 'Een damwand is een grondkering rond de bouwput; hij houdt de grond (en water) tegen tijdens het bouwen.',
    },
    {
      id: 'B.4.k7', toetstermCode: 'B.4.14', type: 'mc',
      prompt: 'Een kelder in het grondwater moet waterdicht zijn. Welke uitvoering ligt voor de hand?',
      options: ['Een waterdichte betonnen bak (kelderbak)', 'Een houten vloer op poeren', 'Een gemetselde spouwmuur zonder coating', 'Een damwand als vloer'],
      correctIndex: 0,
      explanation: 'Onder de grondwaterspiegel wordt de kelder als waterdichte betonnen bak uitgevoerd, met waterkerende voorzieningen.',
    },
  ],
  'B.5': [
    {
      id: 'B.5.k1', toetstermCode: 'B.5.2', type: 'mc',
      prompt: 'Wat is de belangrijkste functie van de spouw in een spouwmuur?',
      options: ['Ruimte voor isolatie en het weren van doorslaand vocht', 'Het dragen van de vloeren', 'Het versieren van de gevel', 'Het afvoeren van rook'],
      correctIndex: 0,
      explanation: 'De spouw biedt plaats voor isolatie en houdt doorslaand regenwater tegen. Het binnenblad draagt.',
    },
    {
      id: 'B.5.k2', toetstermCode: 'B.5.3', type: 'mc',
      prompt: 'Welk metselverband bestaat uitsluitend uit strekken met halfsteens verspringing?',
      options: ['Halfsteensverband', 'Koppenverband', 'Vlaams verband', 'Kruisverband'],
      correctIndex: 0,
      explanation: 'Halfsteensverband = alleen strekken, telkens een halve steen verspringend. Koppenverband is alleen koppen.',
    },
    {
      id: 'B.5.k3', toetstermCode: 'B.5.4', type: 'mc',
      prompt: 'Welk steenformaat is het gangbare Nederlandse baksteenformaat?',
      options: ['Waalformaat', 'Amstelformaat', 'Rijnformaat', 'Deltaformaat'],
      correctIndex: 0,
      explanation: 'Het Waalformaat is het meest gangbare Nederlandse baksteenformaat. (Andere formaten bestaan, maar deze is standaard.)',
    },
    {
      id: 'B.5.k4', toetstermCode: 'B.5.7', type: 'mc',
      prompt: 'Wat is de functie van een latei?',
      options: ['Het metselwerk boven een opening dragen', 'De opening luchtdicht maken', 'De gevel isoleren', 'Het raam laten draaien'],
      correctIndex: 0,
      explanation: 'Een latei overbrugt de opening en draagt het bovenliggende metselwerk af naar de penanten.',
    },
    {
      id: 'B.5.k5', toetstermCode: 'B.5.8', type: 'mc',
      prompt: 'Welke voeg ligt terug ten opzichte van het steenoppervlak en geeft een schaduwwerking?',
      options: ['De verdiepte (schaduw)voeg', 'De platvolle voeg', 'De knipvoeg', 'De doorgestreken voeg'],
      correctIndex: 0,
      explanation: 'Een verdiepte voeg ligt terug en geeft schaduw/reliëf. Een platvolle voeg ligt gelijk met de steen.',
    },
    {
      id: 'B.5.k6', toetstermCode: 'B.5.6', type: 'mc',
      prompt: 'Wat is een klezoor in metselwerk?',
      options: ['Een op maat gehakt (kwart)steentje om het verband te sluiten', 'Een dubbele koppenlaag', 'Een uitkragende siersten', 'Een verticale dilatatievoeg'],
      correctIndex: 0,
      explanation: 'Een klezoor is een in de lengte versmald steentje dat aan het einde van een laag het verband sluitend maakt.',
    },
    {
      id: 'B.5.k7', toetstermCode: 'B.5.9', type: 'mc',
      prompt: 'Wat is de belangrijkste functie van een muurafdekking (ezelsrug/afdeksteen) bovenop een vrijstaande muur?',
      options: ['Inwatering van bovenaf tegengaan', 'De muur dragen', 'De muur isoleren', 'Uitsluitend versiering zonder functie'],
      correctIndex: 0,
      explanation: 'Een muurafdekking leidt regenwater weg van de bovenkant, zodat de muur niet van bovenaf vol water loopt.',
    },
  ],
  'B.6': [
    {
      id: 'B.6.k1', toetstermCode: 'B.6.1', type: 'mc',
      prompt: 'Waaruit bestaat beton in de basis?',
      options: ['Cement, zand, grind en water', 'Kalk, klei en stro', 'Gips, water en vezels', 'Bitumen, zand en vulstof'],
      correctIndex: 0,
      explanation: 'Beton is een mengsel van cement (bindmiddel), toeslag (zand/grind) en water.',
    },
    {
      id: 'B.6.k2', toetstermCode: 'B.6.2', type: 'mc',
      prompt: 'Waarom wordt beton gewapend met staal?',
      options: ['Om de trekkrachten op te nemen die beton zelf slecht aankan', 'Om het beton lichter te maken', 'Om de kleur te bepalen', 'Om sneller uit te harden'],
      correctIndex: 0,
      explanation: 'Beton is druksterk maar trekzwak; het staal neemt de trekkrachten over.',
    },
    {
      id: 'B.6.k3', toetstermCode: 'B.6.3', type: 'mc',
      prompt: 'Wat beschermt de wapening tegen roest en brand?',
      options: ['De betondekking (laag beton over het staal)', 'Een verflaag op de vloer', 'De bekisting', 'De grindnesten'],
      correctIndex: 0,
      explanation: 'De dekking (voldoende beton over de wapening) beschermt tegen corrosie en hitte. Te weinig dekking → betonrot.',
    },
    {
      id: 'B.6.k4', toetstermCode: 'B.6.4', type: 'mc',
      prompt: 'Een holle plek in gestort beton door slechte verdichting heet:',
      options: ['Een grindnest', 'Craquelé', 'Uitbloei', 'Een koudebrug'],
      correctIndex: 0,
      explanation: 'Een grindnest is een holte/samenkleving van grind door onvoldoende verdichten. Craquelé is fijne haarscheurtjes.',
    },
    {
      id: 'B.6.k5', toetstermCode: 'B.6.6', type: 'mc',
      prompt: 'Wat is een nadeel van prefab beton ten opzichte van in het werk gestort beton?',
      options: ['Transport en een hijskraan zijn nodig, en er zijn meer voegen', 'De kwaliteit is minder constant', 'Het is sterk weersafhankelijk in productie', 'De bouwtijd op de bouwplaats is langer'],
      correctIndex: 0,
      explanation: 'Prefab is snel en constant van kwaliteit, maar vraagt transport/kraan en geeft naden/voegen tussen elementen.',
    },
  ],
  'B.7': [
    {
      id: 'B.7.k1', toetstermCode: 'B.7.2', type: 'mc',
      prompt: 'Welk profiel heeft in doorsnede de vorm van een U?',
      options: ['UNP-profiel', 'IPE-profiel', 'HEA-profiel', 'Koker'],
      correctIndex: 0,
      explanation: 'Een UNP-profiel is U-vormig. IPE/HEA zijn I- respectievelijk H-vormig.',
    },
    {
      id: 'B.7.k2', toetstermCode: 'B.7.5', type: 'mc',
      prompt: 'Waarom is onbeschermd staal een risico bij brand?',
      options: ['Het verliest bij hoge temperatuur snel zijn sterkte', 'Het vat vlam en brandt', 'Het geeft giftige rook', 'Het smelt al bij 100 °C'],
      correctIndex: 0,
      explanation: 'Staal brandt niet, maar verliest rond 500 °C fors aan sterkte en kan bezwijken; daarom brandwerende bekleding.',
    },
    {
      id: 'B.7.k3', toetstermCode: 'B.7.1', type: 'mc',
      prompt: 'Welke staalsoort is bestand tegen corrosie zonder verflaag?',
      options: ['Roestvast staal (RVS)', 'Gietstaal', 'Constructiestaal S235', 'Betonstaal FeB500'],
      correctIndex: 0,
      explanation: 'RVS bevat chroom en corrodeert niet. Gewoon constructie- en betonstaal roesten zonder bescherming.',
    },
    {
      id: 'B.7.k4', toetstermCode: 'B.7.5', type: 'mc',
      prompt: 'Welke behandeling beschermt staal tegen corrosie door een zinklaag aan te brengen?',
      options: ['Thermisch verzinken', 'Poedercoaten', 'Brandwerend bekleden', 'Schooperen met aluminium'],
      correctIndex: 0,
      explanation: 'Thermisch verzinken dompelt staal in gesmolten zink → beschermende zinklaag. Poedercoaten is een gelakte laag.',
    },
    {
      id: 'B.7.k5', toetstermCode: 'B.7.3', type: 'mc',
      prompt: 'Wat is het voordeel van een raatligger (met gaten in het lijf)?',
      options: ['Lichter bij gelijke hoogte, en leidingen kunnen door de gaten', 'Sterker in brand', 'Volledig corrosievrij', 'Goedkoper dan elk ander profiel'],
      correctIndex: 0,
      explanation: 'Een raatligger is licht bij grote hoogte en laat leidingen door de openingen lopen; de sterkte blijft grotendeels behouden.',
    },
  ],
  'B.8': [
    {
      id: 'B.8.k1', toetstermCode: 'B.8.1', type: 'mc',
      prompt: 'Welk non-ferro metaal wordt veel gebruikt voor dakgoten en zet sterk uit bij warmte?',
      options: ['Zink', 'Lood', 'Koper', 'Nikkel'],
      correctIndex: 0,
      explanation: 'Zink wordt veel voor goten gebruikt en heeft een grote uitzetting (uitzetstukken nodig).',
    },
    {
      id: 'B.8.k2', toetstermCode: 'B.8.1', type: 'mc',
      prompt: 'Welk metaal vormt een beschermende groene patina in de buitenlucht?',
      options: ['Koper', 'Zink', 'Aluminium', 'Lood'],
      correctIndex: 0,
      explanation: 'Koper vormt een groene patina (kopercarbonaat) die het onderliggende metaal beschermt.',
    },
    {
      id: 'B.8.k3', toetstermCode: 'B.8.1', type: 'mc',
      prompt: 'Welk zeer buigzaam metaal wordt gebruikt voor loketten/slabben bij schoorstenen?',
      options: ['Lood', 'Aluminium', 'Zink', 'Messing'],
      correctIndex: 0,
      explanation: 'Lood is zeer vervormbaar en waterdicht en wordt gebruikt bij aansluitingen/loketten.',
    },
    {
      id: 'B.8.k4', toetstermCode: 'B.8.4', type: 'mc',
      prompt: 'Messing is een legering van vooral:',
      options: ['Koper en zink', 'Koper en tin', 'IJzer en koolstof', 'Aluminium en magnesium'],
      correctIndex: 0,
      explanation: 'Messing = koper + zink. Brons = koper + tin.',
    },
    {
      id: 'B.8.k5', toetstermCode: 'B.8.2', type: 'mc',
      prompt: 'Welk non-ferro metaal is licht en corrosiebestendig en wordt veel voor kozijnen gebruikt?',
      options: ['Aluminium', 'Lood', 'Zink', 'Koper'],
      correctIndex: 0,
      explanation: 'Aluminium is licht en corrosiebestendig; met thermische onderbreking geschikt voor kozijnen en gevels.',
    },
  ],
  'B.9': [
    {
      id: 'B.9.k1', toetstermCode: 'B.9.3', type: 'mc',
      prompt: 'Welke houtsoort is naaldhout (zachthout)?',
      options: ['Vuren', 'Eiken', 'Meranti', 'Beuken'],
      correctIndex: 0,
      explanation: 'Vuren en grenen zijn naaldhout. Eiken, meranti en beuken zijn loofhout (hardhout).',
    },
    {
      id: 'B.9.k2', toetstermCode: 'B.9.1', type: 'mc',
      prompt: 'Wat is de oorzaak van het "werken" van hout?',
      options: ['Opname en afgifte van vocht (zwellen en krimpen)', 'Blootstelling aan zonlicht', 'De houtsoort verkleurt', 'Aantasting door houtworm'],
      correctIndex: 0,
      explanation: 'Hout zwelt bij vocht en krimpt bij droogte; dat "werken" veroorzaakt kieren en scheuren.',
    },
    {
      id: 'B.9.k3', toetstermCode: 'B.9.2', type: 'mc',
      prompt: 'Wat is de belangrijkste voorwaarde voor houtrot (zwam)?',
      options: ['Langdurige aanwezigheid van vocht', 'Te droge lucht', 'Veel zonlicht', 'Contact met beton'],
      correctIndex: 0,
      explanation: 'Schimmels/zwammen die hout aantasten hebben vocht nodig; droog hout rot niet.',
    },
    {
      id: 'B.9.k4', toetstermCode: 'B.9.4', type: 'mc',
      prompt: 'Welk plaatmateriaal bestaat uit kruislings verlijmde fineerlagen?',
      options: ['Multiplex', 'Spaanplaat', 'MDF', 'OSB'],
      correctIndex: 0,
      explanation: 'Multiplex = kruislings verlijmde fineerlagen (sterk, maatvast). Spaanplaat/MDF zijn van spaanders/vezels.',
    },
    {
      id: 'B.9.k5', toetstermCode: 'B.9.6', type: 'mc',
      prompt: 'Waarvoor staat CLT in de houtbouw?',
      options: ['Cross Laminated Timber (kruislaaghout)', 'Coated Laminated Timber', 'Compact Layered Timber', 'Carbon Laminated Timber'],
      correctIndex: 0,
      explanation: 'CLT = Cross Laminated Timber: kruislings verlijmde massief-houten platen, sterk in twee richtingen.',
    },
  ],
  'B.10': [
    {
      id: 'B.10.k1', toetstermCode: 'B.10.1', type: 'mc',
      prompt: 'Wat is de dagmaat van een kozijn?',
      options: ['De vrije openingsmaat binnenwerks', 'De buitenmaat van het kozijnhout', 'De glasdikte', 'De hoogte van de dorpel'],
      correctIndex: 0,
      explanation: 'De dagmaat is de zichtbare vrije opening. De sponningmaat wordt tot in de sponning gemeten.',
    },
    {
      id: 'B.10.k2', toetstermCode: 'B.10.6', type: 'mc',
      prompt: 'Een deur die vlak binnen het kozijnvlak valt, heet:',
      options: ['Een stompe deur', 'Een opdekdeur', 'Een taatsdeur', 'Een schuifdeur'],
      correctIndex: 0,
      explanation: 'Een stompe deur sluit vlak in het kozijn. Een opdekdeur valt met een rand over het kozijn heen.',
    },
    {
      id: 'B.10.k3', toetstermCode: 'B.10.2', type: 'mc',
      prompt: 'Welk raamtype kantelt om een horizontale as ergens in het midden, zodat boven- en onderzijde tegengesteld bewegen?',
      options: ['Een tuimelraam', 'Een valraam', 'Een draaikiepraam', 'Een schuifraam'],
      correctIndex: 0,
      explanation: 'Een tuimelraam draait om een horizontale as in het midden. Een valraam scharniert onderaan en valt naar binnen/buiten.',
    },
    {
      id: 'B.10.k4', toetstermCode: 'B.10.3', type: 'mc',
      prompt: 'Een kozijn wordt tijdens het metselen meteen mee ingemetseld. Dit is een:',
      options: ['Inmetselkozijn', 'Montagekozijn', 'Stelkozijn', 'Renovatiekozijn'],
      correctIndex: 0,
      explanation: 'Een inmetselkozijn wordt tijdens het metselwerk geplaatst; een montagekozijn wordt later in de opening gezet.',
    },
    {
      id: 'B.10.k5', toetstermCode: 'B.10.5', type: 'mc',
      prompt: 'Wat is de functie van de onderdorpel met waterhol/afwatering onder een kozijn?',
      options: ['Regenwater naar buiten afvoeren en de aansluiting waterdicht maken', 'Het kozijn isoleren', 'De deur laten scharnieren', 'Het glas dragen'],
      correctIndex: 0,
      explanation: 'De (weldorpel/onderdorpel) voert water naar buiten af en houdt de aansluiting met de gevel waterdicht.',
    },
  ],
  'B.11': [
    {
      id: 'B.11.k1', toetstermCode: 'B.11.1', type: 'mc',
      prompt: 'Wat is het belangrijkste voordeel van een kunststof kozijn?',
      options: ['Onderhoudsarm: hoeft niet geschilderd te worden', 'Sterker bij brand dan elk ander materiaal', 'Altijd het goedkoopst', 'Volledig biologisch afbreekbaar'],
      correctIndex: 0,
      explanation: 'Kunststof (PVC) kozijnen hoeven niet geschilderd te worden en zijn onderhoudsarm.',
    },
    {
      id: 'B.11.k2', toetstermCode: 'B.11.2', type: 'mc',
      prompt: 'Wat voorkomt een koudebrug en condens bij een aluminium kozijn?',
      options: ['Een thermische onderbreking in het profiel', 'Een dikker aluminium profiel', 'Enkel glas', 'Meer schroeven'],
      correctIndex: 0,
      explanation: 'Een thermisch onderbroken profiel scheidt de warme en koude zijde, waardoor koudebrug en condens worden voorkomen.',
    },
    {
      id: 'B.11.k3', toetstermCode: 'B.11.1', type: 'mc',
      prompt: 'Voor een grote pui met zeer slanke profielen kiest men vaak:',
      options: ['Staal of aluminium', 'Massief hout', 'PVC', 'Multiplex'],
      correctIndex: 0,
      explanation: 'Staal en aluminium zijn sterk en laten slanke profielen toe; hout en PVC vragen dikkere profielen.',
    },
    {
      id: 'B.11.k4', toetstermCode: 'B.11.1', type: 'mc',
      prompt: 'Een nadeel van kunststof kozijnen ten opzichte van hout is vaak:',
      options: ['Minder goed te repareren en lastiger duurzaam te recyclen dan hout', 'Ze moeten jaarlijks geschilderd worden', 'Ze roesten snel', 'Ze zijn niet leverbaar in kleuren'],
      correctIndex: 0,
      explanation: 'Kunststof is onderhoudsarm, maar lokale reparatie is lastig en de milieu-/recyclingkant is een nadeel t.o.v. hout.',
    },
    {
      id: 'B.11.k5', toetstermCode: 'B.11.2', type: 'mc',
      prompt: 'Waarom werd vroeger vaak enkel glas in stalen kozijnen geplaatst en is dat nu een nadeel?',
      options: ['Staal geleidt warmte sterk en met enkel glas ontstaat veel warmteverlies en condens', 'Staal isoleert juist te goed', 'Glas past niet in staal', 'Stalen kozijnen zijn brandbaar'],
      correctIndex: 0,
      explanation: 'Stalen kozijnen (zonder onderbreking) met enkel glas geven veel warmteverlies en condens — een bekend gebrek bij oudere panden.',
    },
  ],
  'B.12': [
    {
      id: 'B.12.k1', toetstermCode: 'B.12.2', type: 'mc',
      prompt: 'Welke balk vangt bij een trapgat de onderbroken vloerbalken op?',
      options: ['De raveelbalk', 'De strijkbalk', 'De nokbalk', 'De gording'],
      correctIndex: 0,
      explanation: 'Rond een sparing draagt de raveelbalk de afgesneden vloerbalken. De strijkbalk ligt langs de muur.',
    },
    {
      id: 'B.12.k2', toetstermCode: 'B.12.3', type: 'mc',
      prompt: 'Waarom moet een kruipruimte geventileerd zijn?',
      options: ['Om vocht af te voeren en schimmel/houtrot in de vloer te voorkomen', 'Om de fundering te koelen', 'Om geluid te dempen', 'Om ongedierte aan te trekken'],
      correctIndex: 0,
      explanation: 'Ventilatie voert vocht af, zodat de begane-grondvloer droog blijft.',
    },
    {
      id: 'B.12.k3', toetstermCode: 'B.12.2', type: 'mc',
      prompt: 'Aan een woningscheidende wand tussen twee woningen worden vooral eisen gesteld aan:',
      options: ['Geluidsisolatie en brandwerendheid', 'Daglicht en uitzicht', 'Zonwering en koeling', 'Kleur en afwerking'],
      correctIndex: 0,
      explanation: 'Een woningscheidende wand moet geluid tussen buren beperken én brand tegenhouden.',
    },
    {
      id: 'B.12.k4', toetstermCode: 'B.12.1', type: 'mc',
      prompt: 'Waarop rusten bij een houten balklaag de vloerbalken (kinderbinten) meestal?',
      options: ['Op een moerbalk of op de muren', 'Op de gordingen', 'Op de nok', 'Op het dakbeschot'],
      correctIndex: 0,
      explanation: 'De lichtere kinderbinten rusten op zwaardere moerbalken of direct op de dragende muren.',
    },
    {
      id: 'B.12.k5', toetstermCode: 'B.12.4', type: 'mc',
      prompt: 'Optrekkend vocht in een begane-grondvloer/wand ontstaat doordat:',
      options: ['Vocht uit de bodem via capillaire werking omhoog trekt', 'De cv-ketel te warm staat', 'Er te veel geventileerd wordt', 'De dakbedekking lekt'],
      correctIndex: 0,
      explanation: 'Zonder goede vochtkering trekt bodemvocht capillair omhoog in muren/vloeren (optrekkend vocht).',
    },
  ],
  'B.13': [
    {
      id: 'B.13.k1', toetstermCode: 'B.13.1', type: 'mc',
      prompt: 'Een dak met vier hellende vlakken die in één punt samenkomen, is een:',
      options: ['Tentdak', 'Schilddak', 'Zadeldak', 'Lessenaarsdak'],
      correctIndex: 0,
      explanation: 'Vier vlakken naar één punt = tentdak. Een schilddak heeft vier vlakken maar met een nok; een zadeldak heeft twee vlakken.',
    },
    {
      id: 'B.13.k2', toetstermCode: 'B.13.2', type: 'mc',
      prompt: 'Bij welke kapconstructie ontbreken horizontale gordingen?',
      options: ['De sporenkap', 'De gordingenkap', 'De spantenkap', 'De vakwerkkap'],
      correctIndex: 0,
      explanation: 'Een sporenkap heeft alleen sporen (dakbenen), geen gordingen; geschikt voor kleinere overspanningen.',
    },
    {
      id: 'B.13.k3', toetstermCode: 'B.13.4', type: 'mc',
      prompt: 'Wat is doorgaans juist over keramische versus betonnen dakpannen?',
      options: ['Keramische pannen gaan meestal langer mee; betonpannen zijn zwaarder en vaak goedkoper', 'Betonpannen zijn gebakken klei', 'Keramische pannen zijn geperst beton', 'Er is geen verschil in levensduur of gewicht'],
      correctIndex: 0,
      explanation: 'Keramische (gebakken) pannen hebben doorgaans een langere levensduur; betonpannen zijn zwaarder en vaak goedkoper.',
    },
    {
      id: 'B.13.k4', toetstermCode: 'B.13.5', type: 'mc',
      prompt: 'Welke dakbedekking hoort bij een plat dak?',
      options: ['Bitumen of EPDM', 'Keramische dakpannen', 'Leien', 'Riet'],
      correctIndex: 0,
      explanation: 'Platte daken worden waterdicht gemaakt met bitumen of EPDM (rubber). Pannen, leien en riet horen bij hellende daken.',
    },
    {
      id: 'B.13.k5', toetstermCode: 'B.13.3', type: 'mc',
      prompt: 'Waar ligt een kilgoot?',
      options: ['In de binnenhoek waar twee dakvlakken samenkomen', 'Aan de onderrand van het dakvlak', 'Op de nok', 'In de schoorsteen'],
      correctIndex: 0,
      explanation: 'Een kilgoot ligt in de "kil" (binnenhoek) tussen twee dakvlakken. Mast-/bakgoten liggen aan de dakvoet.',
    },
  ],
  'B.14': [
    {
      id: 'B.14.k1', toetstermCode: 'B.14.1', type: 'mc',
      prompt: 'Een trap die halverwege 180° van richting keert via een bordes, heet:',
      options: ['Een halfslagtrap (bordestrap)', 'Een kwartslagtrap', 'Een rechte steektrap', 'Een spiltrap'],
      correctIndex: 0,
      explanation: 'Een halfslagtrap keert 180° (vaak via een bordes). Een kwartslag draait 90°.',
    },
    {
      id: 'B.14.k2', toetstermCode: 'B.14.2', type: 'mc',
      prompt: 'Wat is de aantrede van een trap?',
      options: ['De horizontale diepte van een trede', 'Het verticale hoogteverschil per trede', 'De totale traplengte', 'De breedte van de leuning'],
      correctIndex: 0,
      explanation: 'De aantrede is het horizontale loopvlak; de optrede is de verticale hoogte per trede.',
    },
    {
      id: 'B.14.k3', toetstermCode: 'B.14.3', type: 'mc',
      prompt: 'Je vergroot de optrede bij gelijke verdiepingshoogte. Gevolg?',
      options: ['Minder treden, steiler en korter ruimtebeslag', 'Meer treden en een flauwere trap', 'Geen verandering', 'De trap wordt breder'],
      correctIndex: 0,
      explanation: 'Grotere optreden → minder treden om dezelfde hoogte te halen → steiler en minder ruimtebeslag.',
    },
    {
      id: 'B.14.k4', toetstermCode: 'B.14.1', type: 'mc',
      prompt: 'Welke trap neemt het minste grondoppervlak in?',
      options: ['De spiltrap', 'De rechte steektrap', 'De halfslag-bordestrap', 'De kwartslagtrap'],
      correctIndex: 0,
      explanation: 'Een spiltrap draait om een spil en neemt weinig grondoppervlak in, maar is steiler/minder comfortabel.',
    },
    {
      id: 'B.14.k5', toetstermCode: 'B.14.5', type: 'mc',
      prompt: 'Welke lift gebruikt kabels en een tegengewicht?',
      options: ['De tractielift', 'De hydraulische lift', 'De schroefspindel-lift', 'De roltrap'],
      correctIndex: 0,
      explanation: 'Een tractielift beweegt de kooi met staalkabels en een tegengewicht. Een hydraulische lift duwt met oliedruk.',
    },
  ],
  'B.15': [
    {
      id: 'B.15.k1', toetstermCode: 'B.15.1', type: 'mc',
      prompt: 'Welke kunststof wordt veel gebruikt voor riool- en hemelwaterbuizen?',
      options: ['PVC', 'Polycarbonaat (PC)', 'Perspex (PMMA)', 'EPS'],
      correctIndex: 0,
      explanation: 'PVC is licht, sterk en verlijmbaar — standaard voor riolerings- en hwa-buizen.',
    },
    {
      id: 'B.15.k2', toetstermCode: 'B.15.2', type: 'mc',
      prompt: 'Welk doorzichtig materiaal is het meest slagvast en geschikt voor lichtkoepels?',
      options: ['Polycarbonaat (PC)', 'Perspex (PMMA)', 'Glas', 'PVC'],
      correctIndex: 0,
      explanation: 'Polycarbonaat is zeer slagvast; perspex is ook helder maar breekbaarder.',
    },
    {
      id: 'B.15.k3', toetstermCode: 'B.15.1', type: 'mc',
      prompt: 'Wat kenmerkt een thermoplast?',
      options: ['Wordt zacht bij verwarmen en is opnieuw vormbaar', 'Blijft bij verwarmen keihard', 'Kan nooit gerecycled worden', 'Is altijd doorzichtig'],
      correctIndex: 0,
      explanation: 'Thermoplasten (PE, PVC, PP) worden zacht bij warmte en zijn hersmeltbaar. Thermoharders blijven hard.',
    },
    {
      id: 'B.15.k4', toetstermCode: 'B.15.2', type: 'mc',
      prompt: 'Welke kunststof wordt veel gebruikt voor drinkwater- en gasleidingen (flexibel, in rollen)?',
      options: ['Polyetheen (PE)', 'Polycarbonaat (PC)', 'Perspex (PMMA)', 'PVC hard'],
      correctIndex: 0,
      explanation: 'PE (polyetheen) is taai en flexibel en wordt voor water- en gasleidingen gebruikt.',
    },
    {
      id: 'B.15.k5', toetstermCode: 'B.15.1', type: 'mc',
      prompt: 'Wat is het verschil tussen een thermohard en een thermoplast?',
      options: ['Een thermohard is na uitharden niet meer te vervormen; een thermoplast wel', 'Een thermohard smelt makkelijker', 'Een thermoplast is altijd sterker', 'Er is geen verschil'],
      correctIndex: 0,
      explanation: 'Thermoharders zijn na uitharden onomkeerbaar hard; thermoplasten kun je opnieuw verwarmen en vormen.',
    },
  ],
  'B.16': [
    {
      id: 'B.16.k1', toetstermCode: 'B.16.1', type: 'mc',
      prompt: 'Welk isolatiemateriaal is drukvast en vochtbestendig (geschikt onder vloer/omkeerdak)?',
      options: ['XPS', 'Glaswol', 'Steenwol', 'Vlas'],
      correctIndex: 0,
      explanation: 'XPS is drukvast en neemt geen water op. Minerale wol en vlas zouden vollopen en inzakken.',
    },
    {
      id: 'B.16.k2', toetstermCode: 'B.16.1', type: 'mc',
      prompt: 'Welk materiaal is onbrandbaar en daarom geschikt bij brandwerende toepassingen?',
      options: ['Steenwol', 'EPS', 'XPS', 'PUR'],
      correctIndex: 0,
      explanation: 'Steenwol (van gesteente) is onbrandbaar en hittebestendig; kunststofschuimen smelten/branden.',
    },
    {
      id: 'B.16.k3', toetstermCode: 'B.16.1', type: 'mc',
      prompt: 'Welke isolatiematerialen hebben de laagste lambda (beste isolatie per cm)?',
      options: ['PIR en PUR', 'Glaswol en steenwol', 'EPS en vlas', 'Foamglas en cellulose'],
      correctIndex: 0,
      explanation: 'PIR/PUR hebben de laagste lambda-waarde en isoleren dus het best per cm dikte.',
    },
    {
      id: 'B.16.k4', toetstermCode: 'B.16.1', type: 'mc',
      prompt: 'Wat geldt voor de lambda-waarde (λ)?',
      options: ['Hoe lager, hoe beter het materiaal isoleert', 'Hoe hoger, hoe beter het isoleert', 'Zegt niets over isolatie', 'Geldt alleen voor glas'],
      correctIndex: 0,
      explanation: 'Lambda is de warmtegeleiding: lager = minder geleiding = beter isolerend.',
    },
    {
      id: 'B.16.k5', toetstermCode: 'B.16.1', type: 'mc',
      prompt: 'Welk isolatiemateriaal is plantaardig (bio-based)?',
      options: ['Vlas', 'EPS', 'XPS', 'PIR'],
      correctIndex: 0,
      explanation: 'Vlas is een plantaardig, duurzaam alternatief voor minerale wol en kunststofschuimen.',
    },
  ],

  // ─────────────────── C · Afwerking en installaties ───────────────────
  'C.1': [
    {
      id: 'C.1.k1', toetstermCode: 'C.1.2', type: 'mc',
      prompt: 'Bij een gescheiden rioolstelsel:',
      options: ['Gaan vuilwater en regenwater door aparte buizen', 'Gaat alles door één buis', 'Wordt regenwater binnen opgevangen', 'Is er geen riolering'],
      correctIndex: 0,
      explanation: 'Gescheiden = vuilwater en regenwater apart; zo wordt de zuivering niet met schoon regenwater belast.',
    },
    {
      id: 'C.1.k2', toetstermCode: 'C.1.4', type: 'mc',
      prompt: 'Wat is de functie van een sifon (stankafsluiter)?',
      options: ['Een waterslot dat rioollucht tegenhoudt', 'Het water verwarmen', 'Het water filteren', 'De afvoer versnellen'],
      correctIndex: 0,
      explanation: 'De sifon houdt met een waterslotje rioollucht tegen. Droogstaan laat de geur juist door.',
    },
    {
      id: 'C.1.k3', toetstermCode: 'C.1.4', type: 'mc',
      prompt: 'Waarvoor dient een ontstoppingsstuk?',
      options: ['Een toegang om de leiding door te spuiten bij verstopping', 'Het warme water opslaan', 'De rioollucht verwarmen', 'Het drinkwater onthard maken'],
      correctIndex: 0,
      explanation: 'Een ontstoppingsstuk is een afsluitbare opening om de leiding te inspecteren en te ontstoppen.',
    },
    {
      id: 'C.1.k4', toetstermCode: 'C.1.6', type: 'mc',
      prompt: 'Welk materiaal verwacht je in de buitenriolering van een woning van vóór 1960?',
      options: ['Gres of beton', 'PVC met rubbermanchetten', 'Roestvast staal', 'Polyetheen (PE)'],
      correctIndex: 0,
      explanation: 'Oude buitenriolering is vaak gres of beton; die kunnen scheuren of verzakken. PVC kwam later.',
    },
    {
      id: 'C.1.k5', toetstermCode: 'C.1.8', type: 'mc',
      prompt: 'Hoe bespaart een WTW-douche energie?',
      options: ['De warmte van het wegstromende water verwarmt het koude toevoerwater voor', 'Hij verwarmt de badkamer met een radiator', 'Hij vangt regenwater op', 'Hij zuivert het afvalwater'],
      correctIndex: 0,
      explanation: 'De warmtewisselaar draagt warmte van het afgevoerde douchewater over aan het koude toevoerwater.',
    },
  ],
  'C.2': [
    {
      id: 'C.2.k1', toetstermCode: 'C.2.2', type: 'mc',
      prompt: 'Welk toestel levert warm tapwater én cv-water?',
      options: ['Een combiketel', 'Een losse boiler', 'Een geiser', 'Een WTW-douche'],
      correctIndex: 0,
      explanation: 'Een combiketel verzorgt zowel verwarming als warm tapwater; een boiler of geiser alleen tapwater.',
    },
    {
      id: 'C.2.k2', toetstermCode: 'C.2.7', type: 'mc',
      prompt: 'In welk temperatuurbereik groeit legionella het best?',
      options: ['Ongeveer 25–50 °C', 'Onder 10 °C', 'Boven 70 °C', 'Precies 100 °C'],
      correctIndex: 0,
      explanation: 'Legionella gedijt in stilstaand, lauwwarm water (± 25–50 °C). Daarom warm water ≥ 60 °C houden.',
    },
    {
      id: 'C.2.k3', toetstermCode: 'C.2.6', type: 'mc',
      prompt: 'Waaraan herken je een loden waterleiding?',
      options: ['Grijs, zacht metaal dat je kunt indrukken en dat in bochten loopt', 'Blank koper met soldeernaden', 'Wit kunststof met knelfittingen', 'Verzinkt staal met schroefdraad'],
      correctIndex: 0,
      explanation: 'Lood is grijs, zacht en buigzaam; loden drinkwaterleidingen vormen een gezondheidsrisico.',
    },
    {
      id: 'C.2.k4', toetstermCode: 'C.2.5', type: 'mc',
      prompt: 'Wat doet een hydrofoor?',
      options: ['De waterdruk verhogen', 'Het water onthard maken', 'Legionella doden met UV', 'Regenwater opslaan'],
      correctIndex: 0,
      explanation: 'Een hydrofoor verhoogt de waterdruk, bijvoorbeeld bij te lage netdruk in hoge gebouwen.',
    },
    {
      id: 'C.2.k5', toetstermCode: 'C.2.1', type: 'mc',
      prompt: 'Waar zit doorgaans de hoofdafsluiter en watermeter van een woning?',
      options: ['In de meterkast, bij de wateraansluiting', 'Op zolder bij de cv', 'In de kruipruimte onder de badkamer', 'Buiten bij het riool'],
      correctIndex: 0,
      explanation: 'De watermeter en hoofdkraan zitten bij de wateraansluiting in de meterkast.',
    },
  ],
  'C.3': [
    {
      id: 'C.3.k1', toetstermCode: 'C.3.1', type: 'mc',
      prompt: 'Waar zit de hoofdgaskraan doorgaans?',
      options: ['Bij de gasmeter in de meterkast', 'Bij de cv-ketel', 'In de kruipruimte', 'Buiten op straat'],
      correctIndex: 0,
      explanation: 'De hoofdgaskraan zit bij de gasmeter in de meterkast; daarmee sluit je in één keer af.',
    },
    {
      id: 'C.3.k2', toetstermCode: 'C.3.3', type: 'mc',
      prompt: 'Een woning gaat all-electric. Wat is meestal nodig?',
      options: ['Verzwaring van de elektrische aansluiting/groepenkast', 'Een grotere gasmeter', 'Een extra schoorsteen', 'Dikkere waterleidingen'],
      correctIndex: 0,
      explanation: 'All-electric (koken, warmtepomp) vraagt meer vermogen; verzwaring en extra groepen zijn vaak nodig.',
    },
    {
      id: 'C.3.k3', toetstermCode: 'C.3.1', type: 'mc',
      prompt: 'Waarom heeft elk gastoestel een eigen gaskraan?',
      options: ['Om per toestel de gastoevoer te kunnen afsluiten (veiligheid/onderhoud)', 'Om het gasverbruik te meten', 'Om de druk te verhogen', 'Om het gas te reinigen'],
      correctIndex: 0,
      explanation: 'Een toestelkraan maakt het mogelijk om één toestel af te sluiten voor onderhoud of bij een lek.',
    },
    {
      id: 'C.3.k4', toetstermCode: 'C.3.2', type: 'mc',
      prompt: 'Op een installatietekening loopt een leiding met afsluiters naar kooktoestel én cv-ketel. Waarschijnlijk is dit de:',
      options: ['Gasleiding', 'Hemelwaterafvoer', 'Cv-retourleiding', 'Datakabel'],
      correctIndex: 0,
      explanation: 'Een leiding met toestelkranen naar kooktoestel en cv-ketel is de gasleiding.',
    },
    {
      id: 'C.3.k5', toetstermCode: 'C.3.3', type: 'mc',
      prompt: 'Wat is een reden voor de landelijke overgang naar aardgasvrij wonen?',
      options: ['Minder CO₂-uitstoot en minder afhankelijkheid van aardgas', 'Gas is te goedkoop geworden', 'Gasketels gaan langer mee dan warmtepompen', 'Elektriciteit is altijd duurder'],
      correctIndex: 0,
      explanation: 'De transitie is gericht op CO₂-reductie en minder gasafhankelijkheid, o.a. met warmtepompen en warmtenetten.',
    },
  ],
  'C.4': [
    {
      id: 'C.4.k1', toetstermCode: 'C.4.2', type: 'mc',
      prompt: 'Welk onderdeel beschermt tegen elektrocutie door bij een lekstroom snel uit te schakelen?',
      options: ['De aardlekschakelaar', 'De kWh-meter', 'De hoofdschakelaar', 'De installatieautomaat tegen overbelasting'],
      correctIndex: 0,
      explanation: 'De aardlekschakelaar merkt een lekstroom (bv. via een persoon) en schakelt razendsnel uit.',
    },
    {
      id: 'C.4.k2', toetstermCode: 'C.4.1', type: 'mc',
      prompt: 'Waartoe dient de aarding?',
      options: ['Foutstromen veilig afvoeren zodat metalen delen niet onder spanning blijven', 'De rekening verlagen', 'De waterdruk regelen', 'De ketel ontsteken'],
      correctIndex: 0,
      explanation: 'Aarding voert foutstromen af naar de aarde; samen met de aardlekschakelaar beschermt dit tegen elektrocutie.',
    },
    {
      id: 'C.4.k3', toetstermCode: 'C.4.1', type: 'mc',
      prompt: 'Welke norm regelt in Nederland de eisen aan laagspannings-installaties in gebouwen?',
      options: ['NEN 1010', 'NEN 2580', 'NEN 2767', 'NEN 1006'],
      correctIndex: 0,
      explanation: 'NEN 1010 gaat over veilige laagspannings-installaties. NEN 2580 = oppervlaktes, NEN 2767 = conditiemeting, NEN 1006 = leidingwater.',
    },
    {
      id: 'C.4.k4', toetstermCode: 'C.4.2', type: 'mc',
      prompt: 'Wat beschermt een installatieautomaat (in plaats van de aardlekschakelaar)?',
      options: ['Tegen overbelasting en kortsluiting van een groep', 'Tegen elektrocutie via lekstroom', 'Tegen te lage waterdruk', 'Tegen gaslekkage'],
      correctIndex: 0,
      explanation: 'De installatieautomaat (stop) beschermt de groep tegen te hoge stroom (overbelasting/kortsluiting).',
    },
    {
      id: 'C.4.k5', toetstermCode: 'C.4.4', type: 'mc',
      prompt: 'Waarom krijgt een laadpaal meestal een eigen groep?',
      options: ['Vanwege het hoge, langdurige vermogen dat de auto vraagt', 'Omdat een laadpaal geen aarding nodig heeft', 'Om de watermeter te ontlasten', 'Om gas te besparen'],
      correctIndex: 0,
      explanation: 'Een laadpaal vraagt veel vermogen gedurende lange tijd; een eigen (zware) groep voorkomt overbelasting.',
    },
  ],
  'C.5': [
    {
      id: 'C.5.k1', toetstermCode: 'C.5.1', type: 'mc',
      prompt: 'Wat doet de omvormer bij een PV-installatie?',
      options: ['Gelijkstroom (DC) omzetten naar wisselstroom (AC)', 'Wisselstroom omzetten naar gelijkstroom', 'De panelen koelen', 'Het water verwarmen'],
      correctIndex: 0,
      explanation: 'Panelen leveren DC; de omvormer maakt daar bruikbare AC van voor de woning en het net.',
    },
    {
      id: 'C.5.k2', toetstermCode: 'C.5.2', type: 'mc',
      prompt: 'Wat geeft het wattpiek (Wp) van een paneel aan?',
      options: ['Het maximale vermogen onder standaard testomstandigheden', 'De jaaropbrengst in kWh', 'De terugverdientijd', 'Het gewicht'],
      correctIndex: 0,
      explanation: 'Wp is het piekvermogen onder testcondities; de echte opbrengst hangt af van ligging en weer.',
    },
    {
      id: 'C.5.k3', toetstermCode: 'C.5.3', type: 'mc',
      prompt: 'Wat doet een zonnecollector (zonneboiler)?',
      options: ['Tapwater verwarmen met zonne-energie', 'Elektriciteit opwekken', 'De woning koelen', 'Ventileren'],
      correctIndex: 0,
      explanation: 'Een zonnecollector verwarmt water. PV-panelen wekken juist elektriciteit op.',
    },
    {
      id: 'C.5.k4', toetstermCode: 'C.5.1', type: 'mc',
      prompt: 'Wat betekent "salderen" bij zonnepanelen?',
      options: ['Teruggeleverde en afgenomen stroom tegen elkaar wegstrepen', 'De panelen schoonmaken', 'De omvormer vervangen', 'De hellingshoek instellen'],
      correctIndex: 0,
      explanation: 'Bij salderen wordt de aan het net teruggeleverde stroom verrekend met de afgenomen stroom.',
    },
    {
      id: 'C.5.k5', toetstermCode: 'C.5.1', type: 'mc',
      prompt: 'Welke oriëntatie geeft in Nederland doorgaans de hoogste jaaropbrengst voor PV-panelen?',
      options: ['Op het zuiden', 'Op het noorden', 'Recht naar beneden', 'Maakt geen verschil'],
      correctIndex: 0,
      explanation: 'Zuid-georiënteerde panelen met een schuine hoek vangen in Nederland de meeste zon over het jaar.',
    },
  ],
  'C.6': [
    {
      id: 'C.6.k1', toetstermCode: 'C.6.2', type: 'mc',
      prompt: 'Vloerverwarming werkt met relatief laag water. Onder welk systeem valt dit?',
      options: ['Laagtemperatuurverwarming (LTV)', 'Hoogtemperatuurverwarming (HTV)', 'Lokale verwarming', 'Stralingskachel'],
      correctIndex: 0,
      explanation: 'Vloer-/wandverwarming is LTV en past goed bij een warmtepomp. Radiatoren met een ketel werken vaak op HTV.',
    },
    {
      id: 'C.6.k2', toetstermCode: 'C.6.7', type: 'mc',
      prompt: 'Waarom is een HR-ketel zuiniger dan een VR-ketel?',
      options: ['Hij benut de warmte uit condenserende waterdamp in de rookgassen', 'Hij verbrandt geen gas', 'Hij werkt op zonne-energie', 'Hij heeft geen rookgasafvoer'],
      correctIndex: 0,
      explanation: 'Een HR-ketel condenseert de waterdamp in de rookgassen en wint zo extra warmte terug.',
    },
    {
      id: 'C.6.k3', toetstermCode: 'C.6.5', type: 'mc',
      prompt: 'Via welke warmteoverdracht werkt een radiator vooral?',
      options: ['Convectie', 'Straling', 'Geleiding', 'Verdamping'],
      correctIndex: 0,
      explanation: 'Een radiator verwarmt vooral de langsstromende lucht (convectie), ondanks de naam "straler".',
    },
    {
      id: 'C.6.k4', toetstermCode: 'C.6.8', type: 'mc',
      prompt: 'Een lucht-water-warmtepomp presteert het best met:',
      options: ['Lagetemperatuur-afgifte zoals vloerverwarming', 'Hoge-temperatuur radiatoren', 'Een open haard', 'Elektrische kachels'],
      correctIndex: 0,
      explanation: 'Een warmtepomp is efficiënter naarmate de gevraagde temperatuur lager is; LTV past daar perfect bij.',
    },
    {
      id: 'C.6.k5', toetstermCode: 'C.6.1', type: 'mc',
      prompt: 'Wat is een voorbeeld van lokale verwarming?',
      options: ['Een gaskachel of elektrische kachel per ruimte', 'Een cv-ketel met radiatoren door het hele huis', 'Vloerverwarming vanuit een warmtepomp', 'Een warmtenet'],
      correctIndex: 0,
      explanation: 'Lokale verwarming verwarmt per ruimte (kachel). Centrale verwarming verwarmt vanuit één bron het hele huis.',
    },
    {
      id: 'C.6.k6', toetstermCode: 'C.6.1', type: 'mc',
      prompt: 'Wat is een close-in boiler?',
      options: ['Een klein warmwatertoestel vlak bij het tappunt (bv. onder het aanrecht)', 'Een grote voorraadboiler op zolder', 'Een warmtenet-aansluiting', 'Een zonnecollector'],
      correctIndex: 0,
      explanation: 'Een close-in boiler staat dicht bij het tappunt en levert snel warm water zonder lange leidingverliezen.',
    },
    {
      id: 'C.6.k7', toetstermCode: 'C.6.7', type: 'mc',
      prompt: 'Wat is het principiële verschil tussen een cv-ketel en een warmtepomp?',
      options: ['De ketel verbrandt gas; de warmtepomp verplaatst omgevingswarmte met elektriciteit', 'Beide verbranden gas', 'Beide werken op zonlicht', 'De warmtepomp verbrandt hout'],
      correctIndex: 0,
      explanation: 'Een ketel maakt warmte door verbranding; een warmtepomp onttrekt warmte aan lucht/bodem/water en pompt die op met elektriciteit.',
    },
  ],
  'C.7': [
    {
      id: 'C.7.k1', toetstermCode: 'C.7.1', type: 'mc',
      prompt: 'Wat houdt topkoeling in?',
      options: ['Alleen de warmtepiek wegnemen, niet volledig conditioneren', 'De ruimte volledig tot een setpoint koelen', 'Uitsluitend verwarmen', 'Ventileren zonder koeling'],
      correctIndex: 0,
      explanation: 'Topkoeling neemt alleen de scherpste warmte weg; een echte airco koelt volledig tot een ingestelde temperatuur.',
    },
    {
      id: 'C.7.k2', toetstermCode: 'C.7.1', type: 'mc',
      prompt: 'Een gecombineerd luchtbehandelingssysteem kan:',
      options: ['Zowel verwarmen als koelen (en vaak ventileren)', 'Alleen verwarmen', 'Alleen koelen', 'Alleen ventileren'],
      correctIndex: 0,
      explanation: 'Een gecombineerd systeem behandelt de lucht: verwarmen én koelen, meestal met ventilatie.',
    },
    {
      id: 'C.7.k3', toetstermCode: 'C.7.1', type: 'mc',
      prompt: 'Waarom kiest men in woningen vaker topkoeling dan volledige airco?',
      options: ['Eenvoudiger en zuiniger dan volledige koeling', 'Topkoeling koelt sterker', 'Airco kan niet in woningen', 'Topkoeling verwarmt tapwater'],
      correctIndex: 0,
      explanation: 'Voor woningen volstaat topkoeling vaak; volledige airco is duurder en energie-intensiever.',
    },
    {
      id: 'C.7.k4', toetstermCode: 'C.7.1', type: 'mc',
      prompt: 'Een warmtepomp die in de zomer koud water door de vloerverwarming stuurt, levert:',
      options: ['Passieve/actieve vloerkoeling (een vorm van topkoeling)', 'Volledige airconditioning', 'Alleen ventilatie', 'Warm tapwater'],
      correctIndex: 0,
      explanation: 'Koud water door de vloer geeft een milde koeling (vloerkoeling), vergelijkbaar met topkoeling.',
    },
    {
      id: 'C.7.k5', toetstermCode: 'C.7.1', type: 'mc',
      prompt: 'Wat is een nadeel van een split-airco (buiten- en binnenunit)?',
      options: ['Energieverbruik en (bij de buitenunit) geluid/uiterlijk', 'Hij kan niet koelen', 'Hij werkt zonder elektriciteit', 'Hij verwarmt nooit'],
      correctIndex: 0,
      explanation: 'Een split-airco koelt effectief maar verbruikt energie en de buitenunit geeft geluid en beïnvloedt het aanzicht.',
    },
  ],
  'C.8': [
    {
      id: 'C.8.k1', toetstermCode: 'C.8.1', type: 'mc',
      prompt: 'Welke rookmelder is in woningen de standaard en verplicht?',
      options: ['De optische rookmelder', 'De ionisatiemelder', 'De thermische melder', 'De koolmonoxidemelder'],
      correctIndex: 0,
      explanation: 'De optische rookmelder (lichtverstrooiing) is standaard en verplicht. Een CO-melder meet iets anders (koolmonoxide).',
    },
    {
      id: 'C.8.k2', toetstermCode: 'C.8.5', type: 'mc',
      prompt: 'Waar staat WBDBO voor?',
      options: ['Weerstand tegen BrandDoorslag en BrandOverslag', 'Wettelijke Bouw- en Brand-Documentatie', 'Warmte- en Brand-Doorlatendheid Bouwonderdelen', 'Waarborg Brandmelding Bewaking Objecten'],
      correctIndex: 0,
      explanation: 'WBDBO is de tijd dat een scheiding brand tegenhoudt, zowel dwars door de constructie (doorslag) als buitenom (overslag).',
    },
    {
      id: 'C.8.k3', toetstermCode: 'C.8.5', type: 'mc',
      prompt: 'Wat is het doel van brandcompartimentering?',
      options: ['Brand en rook een bepaalde tijd tot één deel van het gebouw beperken', 'De brand sneller laten uitbranden', 'De vluchtweg verkorten', 'Rookmelders vervangen'],
      correctIndex: 0,
      explanation: 'Compartimentering begrenst brand en rook een bepaalde tijd, zodat mensen kunnen vluchten en de brandweer kan ingrijpen.',
    },
    {
      id: 'C.8.k4', toetstermCode: 'C.8.2', type: 'mc',
      prompt: 'Hoe doof je een vlam in een pan met hete olie?',
      options: ['Met een deksel of blusdeken (zuurstof afsluiten)', 'Met een emmer water', 'Door er meel op te gooien', 'Door de pan buiten te zetten'],
      correctIndex: 0,
      explanation: 'Water in hete olie verdampt explosief (steekvlam). Een deksel of blusdeken sluit de zuurstof af.',
    },
    {
      id: 'C.8.k5', toetstermCode: 'C.8.5', type: 'mc',
      prompt: 'Wat is de belangrijkste eis aan een vluchtweg?',
      options: ['Veilig, herkenbaar en binnen de vereiste tijd naar buiten leiden', 'Zo kort mogelijk zijn, ongeacht veiligheid', 'Door de meest brandgevaarlijke ruimte lopen', 'Altijd via de lift gaan'],
      correctIndex: 0,
      explanation: 'Een vluchtweg moet mensen veilig en herkenbaar naar buiten (of een veilig compartiment) leiden; niet via liften.',
    },
  ],
  'C.9': [
    {
      id: 'C.9.k1', toetstermCode: 'C.9.1', type: 'mc',
      prompt: 'Natuurlijke toevoer via roosters + mechanische afvoer via een box is:',
      options: ['Systeem C', 'Systeem A', 'Systeem B', 'Systeem D'],
      correctIndex: 0,
      explanation: 'Systeem C = natuurlijke toevoer, mechanische afvoer — het meest voorkomend in Nederlandse woningen.',
    },
    {
      id: 'C.9.k2', toetstermCode: 'C.9.1', type: 'mc',
      prompt: 'Mechanische toevoer én afvoer met warmteterugwinning is:',
      options: ['Systeem D', 'Systeem C', 'Systeem B', 'Systeem A'],
      correctIndex: 0,
      explanation: 'Gebalanceerde ventilatie met WTW = systeem D; de warme afvoerlucht verwarmt de verse toevoerlucht voor.',
    },
    {
      id: 'C.9.k3', toetstermCode: 'C.9.1', type: 'mc',
      prompt: 'Volledig natuurlijke ventilatie (toe- én afvoer zonder ventilator) is:',
      options: ['Systeem A', 'Systeem B', 'Systeem C', 'Systeem D'],
      correctIndex: 0,
      explanation: 'Systeem A is volledig natuurlijk (roosters/kanalen zonder mechanische hulp).',
    },
    {
      id: 'C.9.k4', toetstermCode: 'C.9.3', type: 'mc',
      prompt: 'Een shuntkanaal voorkomt dat:',
      options: ['Lucht/geur van de ene woning bij de buren overslaat', 'Regenwater het kanaal binnenkomt', 'De ventilator te hard draait', 'Het kanaal bevriest'],
      correctIndex: 0,
      explanation: 'Een shuntkanaal geeft elke woning een eigen nevenkanaal op een gezamenlijk hoofdkanaal, zodat lucht niet overslaat.',
    },
    {
      id: 'C.9.k5', toetstermCode: 'C.9.2', type: 'mc',
      prompt: 'Wat is het voordeel van systeem D (WTW)?',
      options: ['Warmteterugwinning uit de afvoerlucht → minder warmteverlies', 'Er is geen enkele ventilator nodig', 'Het werkt zonder kanalen', 'Het koelt de woning volledig'],
      correctIndex: 0,
      explanation: 'De WTW-unit hergebruikt de warmte uit de afvoerlucht om de verse lucht voor te verwarmen: energiewinst.',
    },
  ],
  'C.10': [
    {
      id: 'C.10.k1', toetstermCode: 'C.10.1', type: 'mc',
      prompt: 'Waar staat PKVW voor?',
      options: ['Politiekeurmerk Veilig Wonen', 'Provinciaal Keurmerk Vastgoed Waardering', 'Particulier Keurmerk Verwarming en Water', 'Publiek Keurmerk Verduurzaamd Wonen'],
      correctIndex: 0,
      explanation: 'PKVW = Politiekeurmerk Veilig Wonen, gericht op inbraakpreventie (hang- en sluitwerk, verlichting, zicht).',
    },
    {
      id: 'C.10.k2', toetstermCode: 'C.10.2', type: 'mc',
      prompt: 'Welke aansluiting biedt doorgaans de snelste, meest stabiele internetverbinding?',
      options: ['Glasvezel', 'Koperen telefoonlijn', 'Het gasnet', 'De waterleiding'],
      correctIndex: 0,
      explanation: 'Glasvezel (data via licht) is sneller en stabieler dan een koperen verbinding.',
    },
    {
      id: 'C.10.k3', toetstermCode: 'C.10.3', type: 'mc',
      prompt: 'Wat is domotica?',
      options: ['Automatisering en centrale bediening van installaties in huis', 'Een systeem voor regenwaterbuffering', 'Een funderingstype', 'Een vorm van gevelisolatie'],
      correctIndex: 0,
      explanation: 'Domotica is huisautomatisering: slim aansturen van licht, verwarming, zonwering en beveiliging.',
    },
    {
      id: 'C.10.k4', toetstermCode: 'C.10.1', type: 'mc',
      prompt: 'Welke maatregel valt onder organisatorische/bouwkundige inbraakpreventie (PKVW)?',
      options: ['Goede buitenverlichting en zicht op de voordeur', 'Een groter energielabel', 'Een dikkere spouwisolatie', 'Een hogere Rc-waarde'],
      correctIndex: 0,
      explanation: 'Naast SKG-sluitwerk let PKVW op verlichting, zichtlijnen en indeling — die verkleinen de inbraakkans.',
    },
    {
      id: 'C.10.k5', toetstermCode: 'C.10.2', type: 'mc',
      prompt: 'Waarvoor dient een centrale antenne-/data-aansluiting (CAI/coax of glasvezel) in de meterkast?',
      options: ['Het binnenbrengen en verdelen van tv-/internetsignaal', 'Het afvoeren van rookgassen', 'Het verhogen van de waterdruk', 'Het aarden van de installatie'],
      correctIndex: 0,
      explanation: 'De data-aansluiting brengt tv/internet binnen en verdeelt het naar de ruimten.',
    },
  ],
  'C.11': [
    {
      id: 'C.11.k1', toetstermCode: 'C.11.1', type: 'mc',
      prompt: 'Wat is HR++-glas?',
      options: ['Dubbel glas met coating en gasvulling voor betere isolatie', 'Enkel glas', 'Gehard veiligheidsglas', 'Brandwerend glas'],
      correctIndex: 0,
      explanation: 'HR++-glas is dubbel glas met een metaalcoating en edelgas in de spouw; isoleert veel beter dan gewoon dubbelglas.',
    },
    {
      id: 'C.11.k2', toetstermCode: 'C.11.2', type: 'mc',
      prompt: 'Wat geldt voor de Ug-waarde van glas?',
      options: ['Hoe lager, hoe beter het isoleert', 'Hoe hoger, hoe beter het isoleert', 'Zegt niets over isolatie', 'Gaat alleen over geluid'],
      correctIndex: 0,
      explanation: 'De U-waarde is het warmteverlies: lager = beter isolerend. (Bij Rc is het juist andersom.)',
    },
    {
      id: 'C.11.k3', toetstermCode: 'C.11.1', type: 'mc',
      prompt: 'Welk glas blijft na breuk dankzij een folie in één geheel hangen (letselwerend)?',
      options: ['Gelaagd glas', 'Gehard glas', 'Enkel floatglas', 'Draadglas'],
      correctIndex: 0,
      explanation: 'Gelaagd glas heeft een taaie folie; de scherven blijven eraan plakken. Gehard glas valt uiteen in stompe korrels.',
    },
    {
      id: 'C.11.k4', toetstermCode: 'C.11.5', type: 'mc',
      prompt: 'Condens tússen de twee bladen van dubbelglas betekent:',
      options: ['De randafdichting is doorgeslagen; de ruit is defect', 'Het glas is enkel', 'Het is zonwerend glas', 'Er zit te veel argon in'],
      correctIndex: 0,
      explanation: 'Damp tussen de bladen wijst op een lekke randafdichting; de isolatieruit is defect en wordt vervangen.',
    },
    {
      id: 'C.11.k5', toetstermCode: 'C.11.1', type: 'mc',
      prompt: 'Welk oud glastype heeft een ingewalste metalen draadstructuur en werd vroeger als (beperkt) veiligheids-/brandglas gezien?',
      options: ['Draadglas', 'Gelaagd glas', 'HR++-glas', 'Zonwerend glas'],
      correctIndex: 0,
      explanation: 'Draadglas heeft een metalen draadnet; het houdt scherven bijeen maar is géén modern veiligheidsglas.',
    },
    {
      id: 'C.11.k6', toetstermCode: 'C.11.1', type: 'mc',
      prompt: 'Wat is HR+++-glas?',
      options: ['Triple glas: drie glasbladen met twee geïsoleerde spouwen', 'Enkel glas met folie', 'Gehard glas', 'Draadglas'],
      correctIndex: 0,
      explanation: 'HR+++ is triple glas (drie bladen, twee spouwen met coating/gas) en isoleert nog beter dan HR++.',
    },
    {
      id: 'C.11.k7', toetstermCode: 'C.11.4', type: 'mc',
      prompt: 'Wat is een vliesgevel (structurele beglazing)?',
      options: ['Een niet-dragende glazen buitenhuid die vóór de draagconstructie hangt', 'Een dragende glazen kolom', 'Een dubbele dakbedekking', 'Een funderingstype'],
      correctIndex: 0,
      explanation: 'Een vliesgevel is een niet-dragende, doorgaans glazen gevelhuid die als "vlies" vóór de constructie is gehangen.',
    },
  ],
  'C.12': [
    {
      id: 'C.12.k1', toetstermCode: 'C.12.1', type: 'mc',
      prompt: 'Welk keurmerk geeft de inbraakwerendheid van hang- en sluitwerk aan?',
      options: ['SKG (sterren)', 'KOMO', 'CE', 'FSC'],
      correctIndex: 0,
      explanation: 'SKG-sterren (1–3) geven de inbraakwerendheid aan. KOMO is een algemeen bouwkeurmerk, FSC gaat over hout.',
    },
    {
      id: 'C.12.k2', toetstermCode: 'C.12.1', type: 'mc',
      prompt: 'Waarom is een meerpuntsluiting inbraakwerender?',
      options: ['De deur vergrendelt op meerdere punten in het kozijn', 'De deur is lichter', 'Er is geen sleutel nodig', 'De deur sluit sneller'],
      correctIndex: 0,
      explanation: 'Vergrendeling op meerdere punten (boven, midden, onder) maakt de deur veel moeilijker te forceren.',
    },
    {
      id: 'C.12.k3', toetstermCode: 'C.12.1', type: 'mc',
      prompt: 'Waartegen beschermt een kerntrekbeveiliging op een cilinderslot?',
      options: ['Het uit de deur trekken van de cilinder (kerntrekken)', 'Het doorzagen van de deur', 'Het inslaan van het raam', 'Het liften van de deur uit de scharnieren'],
      correctIndex: 0,
      explanation: 'Kerntrekbeveiliging (en degelijk beslag) voorkomt dat inbrekers de cilinder eruit trekken.',
    },
    {
      id: 'C.12.k4', toetstermCode: 'C.12.1', type: 'mc',
      prompt: 'Wat is de functie van een scharnier met een pen die niet te verwijderen is (of borgpen)?',
      options: ['Voorkomen dat de deur aan de scharnierzijde wordt gelicht', 'De deur sneller laten sluiten', 'De deur isoleren', 'Het slot smeren'],
      correctIndex: 0,
      explanation: 'Veiligheidsscharnieren/borgpennen voorkomen dat een deur aan de scharnierzijde uit het kozijn wordt gelicht.',
    },
    {
      id: 'C.12.k5', toetstermCode: 'C.12.1', type: 'mc',
      prompt: 'Welk onderdeel bepaalt met welke sleutel een deur te openen is en is los te vervangen?',
      options: ['De cilinder', 'De kruk', 'Het scharnier', 'De dorpel'],
      correctIndex: 0,
      explanation: 'De (euro)cilinder bevat het sluitmechanisme en de sleutelcombinatie; hij is apart te vervangen.',
    },
  ],
  'C.13': [
    {
      id: 'C.13.k1', toetstermCode: 'C.13.2', type: 'mc',
      prompt: 'Wat is de juiste opbouw van een verfsysteem op kaal hout?',
      options: ['Grondverf → voorlak → aflak', 'Aflak → grondverf → voorlak', 'Voorlak → aflak → grondverf', 'Alleen aflak'],
      correctIndex: 0,
      explanation: 'Eerst grondverf (hecht), dan voorlak (vult/bouwt op), dan aflak (beschermende toplaag).',
    },
    {
      id: 'C.13.k2', toetstermCode: 'C.13.6', type: 'mc',
      prompt: 'Waar gaat de "Rutschwerte" (R-waarde) van een vloertegel over?',
      options: ['De stroefheid/antislip', 'De hardheid', 'De kleurechtheid', 'De waterdichtheid'],
      correctIndex: 0,
      explanation: 'De R-waarde (R9–R13) geeft de antislipklasse aan; in natte ruimten kies je een hogere waarde.',
    },
    {
      id: 'C.13.k3', toetstermCode: 'C.13.4', type: 'mc',
      prompt: 'Wat is stucwerk?',
      options: ['Een gladde afwerklaag van gips- of kalkmortel op de wand', 'Een laag tegels', 'Een houten betimmering', 'Een isolatieplaat'],
      correctIndex: 0,
      explanation: 'Stucwerk is een dunne, gladde pleisterlaag die de wand vlak en schilder-/behangklaar maakt.',
    },
    {
      id: 'C.13.k4', toetstermCode: 'C.13.8', type: 'mc',
      prompt: 'Welke vloerafwerking is naadloos gegoten en daarna uitgehard?',
      options: ['Een gietvloer', 'Een parketvloer', 'Een tapijtvloer', 'Een tegelvloer'],
      correctIndex: 0,
      explanation: 'Een gietvloer wordt vloeibaar aangebracht en hardt naadloos uit. Parket, tapijt en tegels bestaan uit delen.',
    },
    {
      id: 'C.13.k5', toetstermCode: 'C.13.9', type: 'mc',
      prompt: 'Holklinkende wandtegels wijzen op:',
      options: ['Onvoldoende hechting (holle ruimte achter de tegel)', 'Te harde tegels', 'Te veel daglicht', 'Een te brede voeg'],
      correctIndex: 0,
      explanation: 'Holklinkende tegels hebben onvoldoende lijmcontact met de ondergrond en kunnen loslaten.',
    },
  ],
  'C.14': [
    {
      id: 'C.14.k1', toetstermCode: 'C.14.1', type: 'mc',
      prompt: 'Tot welke hoofdgroep behoort graniet?',
      options: ['Stollingsgesteente', 'Afzettingsgesteente', 'Metamorf gesteente', 'Kunststeen'],
      correctIndex: 0,
      explanation: 'Graniet is gestold uit magma → stollingsgesteente. Zandsteen = afzetting; marmer/leisteen = metamorf.',
    },
    {
      id: 'C.14.k2', toetstermCode: 'C.14.1', type: 'mc',
      prompt: 'Marmer en leisteen zijn:',
      options: ['Metamorf gesteente', 'Stollingsgesteente', 'Afzettingsgesteente', 'Kunststeen'],
      correctIndex: 0,
      explanation: 'Marmer (uit kalksteen) en leisteen (uit klei) zijn door druk en hitte omgevormd: metamorf.',
    },
    {
      id: 'C.14.k3', toetstermCode: 'C.14.1', type: 'mc',
      prompt: 'Welke natuursteen is het hardst en meest slijt-/zuurbestendig (geschikt voor werkbladen)?',
      options: ['Graniet', 'Marmer', 'Travertijn', 'Zandsteen'],
      correctIndex: 0,
      explanation: 'Graniet is zeer hard en zuurbestendig. Marmer en travertijn zijn kalkhoudend en gevoelig voor zuren/krassen.',
    },
    {
      id: 'C.14.k4', toetstermCode: 'C.14.3', type: 'mc',
      prompt: 'Welke oppervlaktebewerking maakt natuursteen spiegelglad en glanzend?',
      options: ['Polijsten', 'Frijnen', 'Boucharderen', 'Zoeten'],
      correctIndex: 0,
      explanation: 'Polijsten geeft een spiegelglad, glanzend oppervlak. Frijnen/boucharderen maken juist een ruwer, stroef vlak.',
    },
    {
      id: 'C.14.k5', toetstermCode: 'C.14.3', type: 'mc',
      prompt: 'Welke bewerking geeft een stroef, antislip oppervlak met fijne parallelle groeven (bv. traptreden)?',
      options: ['Frijnen', 'Polijsten', 'Zoeten', 'Slijpen tot hoogglans'],
      correctIndex: 0,
      explanation: 'Frijnen maakt fijne parallelle groeven en dus grip; polijsten/zoeten maken juist glad.',
    },
  ],

  // ─────────────── D · Kwaliteit, onderhoud, duurzaamheid ───────────────
  'D.1': [
    {
      id: 'D.1.k1', toetstermCode: 'D.1.1', type: 'mc',
      prompt: 'Wat is een MJOP?',
      options: ['Een meerjarenonderhoudsplan met onderhoud en kosten vooruit gepland', 'Een maandelijkse energierekening', 'Een milieuvergunning', 'Een makelaarscontract'],
      correctIndex: 0,
      explanation: 'Een MJOP plant per bouwdeel het onderhoud en de kosten meerjarig, vaak met NEN 2767-conditiemeting.',
    },
    {
      id: 'D.1.k2', toetstermCode: 'D.1.2', type: 'mc',
      prompt: 'Wat betekent conditiescore 1 volgens NEN 2767?',
      options: ['Uitstekend (nagenoeg nieuw)', 'Zeer slecht (bijna afgekeurd)', 'Gemiddeld', 'Niet te beoordelen'],
      correctIndex: 0,
      explanation: 'NEN 2767 loopt van 1 (uitstekend) tot 6 (zeer slecht). Een hoger cijfer is dus slechter.',
    },
    {
      id: 'D.1.k3', toetstermCode: 'D.1.4', type: 'mc',
      prompt: 'Wat is planmatig (preventief) onderhoud?',
      options: ['Vooraf gepland onderhoud om gebreken te voorkomen', 'Onderhoud pas nadat iets kapot is', 'Onderhoud dat nooit nodig is', 'Sloop en nieuwbouw'],
      correctIndex: 0,
      explanation: 'Preventief/planmatig onderhoud wordt vooraf ingepland (basis van een MJOP). Correctief onderhoud volgt ná een gebrek.',
    },
    {
      id: 'D.1.k4', toetstermCode: 'D.1.3', type: 'mc',
      prompt: 'Wat is het verschil tussen renovatie en groot onderhoud?',
      options: ['Renovatie verbetert/verhoogt de kwaliteit; groot onderhoud herstelt naar de oorspronkelijke staat', 'Ze betekenen precies hetzelfde', 'Groot onderhoud is altijd duurder dan renovatie', 'Renovatie mag alleen bij monumenten'],
      correctIndex: 0,
      explanation: 'Renovatie tilt de woning naar een hoger niveau; (groot) onderhoud herstelt de bestaande kwaliteit.',
    },
    {
      id: 'D.1.k5', toetstermCode: 'D.1.6', type: 'mc',
      prompt: 'Welk bouwonderdeel heeft doorgaans de langste levensduur?',
      options: ['De draagconstructie/fundering', 'Het schilderwerk', 'De cv-ketel', 'De keukeninrichting'],
      correctIndex: 0,
      explanation: 'De draagconstructie gaat vele decennia mee; schilderwerk, ketel en keuken hebben een veel kortere levensduur.',
    },
  ],
  'D.2': [
    {
      id: 'D.2.k1', toetstermCode: 'D.2.1', type: 'mc',
      prompt: 'Afbladderende verf, zacht hout onderin kozijnen en open naden wijzen op:',
      options: ['Achterstallig schilder-/houtwerk met (beginnende) houtrot', 'Een verzakte fundering', 'Niet-isolerend glas', 'Een niet-vergunde uitbouw'],
      correctIndex: 0,
      explanation: 'Dit zijn onderhoudssignalen (schilderwerk/houtrot), geen funderings- of vergunningskwestie.',
    },
    {
      id: 'D.2.k2', toetstermCode: 'D.2.2', type: 'mc',
      prompt: 'Diagonale, trapsgewijze scheuren door steen én voeg, breder naar boven, wijzen meestal op:',
      options: ['Zetting/verzakking van (een deel van) de fundering', 'Normale krimp van vers metselwerk', 'Slecht schilderwerk', 'Te veel spouwisolatie'],
      correctIndex: 0,
      explanation: 'Zulke scheuren duiden op ongelijkmatige zetting van de fundering — een constructief signaal.',
    },
    {
      id: 'D.2.k3', toetstermCode: 'D.2.1', type: 'mc',
      prompt: 'Roeststrepen en afgespat beton met zichtbare wapening aan een galerijplaat duiden op:',
      options: ['Betonrot; nader constructief onderzoek nodig', 'Normale vervuiling; alleen reinigen', 'Houtrot; hout vervangen', 'Vochtdoorslag door de spouw'],
      correctIndex: 0,
      explanation: 'Roestende, uitzettende wapening die het beton afdrukt = betonrot; bij dragende platen is onderzoek geboden.',
    },
    {
      id: 'D.2.k4', toetstermCode: 'D.2.1', type: 'mc',
      prompt: 'Bruine vlekken en zoutuitslag laag op een binnenmuur wijzen vaak op:',
      options: ['Optrekkend vocht uit de bodem', 'Een lekkend dak', 'Te droge lucht', 'Een koudebrug bij het dak'],
      correctIndex: 0,
      explanation: 'Vocht en zoutuitbloei onderaan een muur wijzen op optrekkend (capillair) bodemvocht.',
    },
    {
      id: 'D.2.k5', toetstermCode: 'D.2.2', type: 'mc',
      prompt: 'Bij het beoordelen van een plat dak zie je plassen die lang blijven staan. Welk gevolg is het grootste risico?',
      options: ['Extra belasting en versnelde veroudering/lekkage van de dakbedekking', 'Een beter energielabel', 'Meer daglicht binnen', 'Een sterkere draagconstructie'],
      correctIndex: 0,
      explanation: 'Blijvend water (plasvorming) belast de dakbedekking, versnelt veroudering en vergroot de kans op lekkage.',
    },
  ],
  'D.3': [
    {
      id: 'D.3.k1', toetstermCode: 'D.3.5', type: 'mc',
      prompt: 'Wat geldt voor de Rc-waarde van een dichte constructie?',
      options: ['Hoe hoger, hoe beter geïsoleerd', 'Hoe lager, hoe beter geïsoleerd', 'Zegt iets over geluid', 'Zegt iets over brand'],
      correctIndex: 0,
      explanation: 'Rc is de warmteweerstand van een dichte constructie: hoger = beter. (Bij de U-waarde is het andersom.)',
    },
    {
      id: 'D.3.k2', toetstermCode: 'D.3.3', type: 'mc',
      prompt: 'Aan welke zijde van de isolatie hoort de dampremmende folie?',
      options: ['Aan de warme (binnen)zijde', 'Aan de koude (buiten)zijde', 'In het midden', 'Dat maakt niet uit'],
      correctIndex: 0,
      explanation: '"Damp remmen aan de warme kant": zo dringt vochtige binnenlucht niet tot de koude zijde door en condenseert daar niet.',
    },
    {
      id: 'D.3.k3', toetstermCode: 'D.3.4', type: 'mc',
      prompt: 'Wat is een koudebrug?',
      options: ['Een plek met minder isolatie waar veel warmte weglekt en condens kan ontstaan', 'Een koelinstallatie', 'Een brug over koud water', 'Een type plat dak'],
      correctIndex: 0,
      explanation: 'Bij een koudebrug (bv. doorlopende betonvloer naar balkon) lekt warmte weg en kan condens/schimmel ontstaan.',
    },
    {
      id: 'D.3.k4', toetstermCode: 'D.3.9', type: 'mc',
      prompt: 'Voetstappen en schuivende stoelen die je bij de buren hoort, zijn vooral:',
      options: ['Contactgeluid (via de constructie)', 'Luchtgeluid (via de lucht)', 'Galm', 'Installatiegeluid'],
      correctIndex: 0,
      explanation: 'Trillingen die rechtstreeks in de constructie komen = contactgeluid. Praten/muziek = luchtgeluid.',
    },
    {
      id: 'D.3.k5', toetstermCode: 'D.3.8', type: 'mc',
      prompt: 'Wat geeft de BENG 3-indicator aan?',
      options: ['Het aandeel hernieuwbare energie (%)', 'De energiebehoefte in kWh/m²', 'Het primair fossiel energiegebruik', 'De geluidsisolatie'],
      correctIndex: 0,
      explanation: 'BENG 1 = energiebehoefte, BENG 2 = primair fossiel gebruik, BENG 3 = aandeel hernieuwbare energie.',
    },
    {
      id: 'D.3.k6', toetstermCode: 'D.3.2', type: 'mc',
      prompt: 'Waarvan hangt de thermische behaaglijkheid (comfort) in een ruimte vooral af?',
      options: ['Van temperatuur, luchtvochtigheid, tocht en stralingstemperatuur samen', 'Alleen van de luchttemperatuur', 'Alleen van de luchtvochtigheid', 'Alleen van de geluidsisolatie'],
      correctIndex: 0,
      explanation: 'Comfort is een samenspel van luchttemperatuur, vochtigheid, luchtsnelheid (tocht) en de stralingstemperatuur van wanden.',
    },
    {
      id: 'D.3.k7', toetstermCode: 'D.3.3', type: 'mc',
      prompt: 'Waarvoor dient een dampopen (ademende) folie aan de koude zijde van een constructie?',
      options: ['Wind- en waterdicht maken, maar vocht van binnenuit laten ontsnappen', 'De constructie volledig dampdicht afsluiten', 'De isolatie dragen', 'Geluid weren'],
      correctIndex: 0,
      explanation: 'Een dampopen folie aan de koude zijde houdt wind en water tegen maar laat waterdamp naar buiten ontsnappen, zodat vocht niet opgesloten raakt.',
    },
  ],
  'D.4': [
    {
      id: 'D.4.k1', toetstermCode: 'D.4.2', type: 'mc',
      prompt: 'Tussen welke uitersten loopt de energielabelschaal voor woningen?',
      options: ['A (zeer zuinig) tot G (zeer onzuinig)', '1 tot 10', 'Rood tot groen zonder letters', 'A tot D'],
      correctIndex: 0,
      explanation: 'De schaal loopt van A (tegenwoordig tot A++++) tot G. Het label is verplicht bij verkoop en verhuur.',
    },
    {
      id: 'D.4.k2', toetstermCode: 'D.4.2', type: 'mc',
      prompt: 'Hoe komt een geldig energielabel tot stand?',
      options: ['Een erkend energieadviseur neemt de woning op en registreert het', 'De eigenaar bepaalt het zelf online', 'De makelaar geeft het af', 'Het volgt uit de WOZ-waarde'],
      correctIndex: 0,
      explanation: 'Sinds 2021 stelt een erkend adviseur het label op na opname; verkoop zonder geldig label kan een boete opleveren.',
    },
    {
      id: 'D.4.k3', toetstermCode: 'D.4.8', type: 'mc',
      prompt: 'Aan welke eis moeten de meeste kantoren sinds 2023 voldoen?',
      options: ['Minimaal energielabel C', 'Minimaal energielabel A', 'Volledig gasloos', 'Zonnepanelen op het dak'],
      correctIndex: 0,
      explanation: 'Sinds 2023 geldt voor de meeste kantoren (vanaf 100 m²) minimaal label C, anders mag het niet als kantoor in gebruik blijven.',
    },
    {
      id: 'D.4.k4', toetstermCode: 'D.4.5', type: 'mc',
      prompt: 'Wat is de kern van circulair bouwen?',
      options: ['Herbruikbare materialen en zo min mogelijk afval, gericht op hergebruik', 'Zo goedkoop mogelijk bouwen', 'Alles in beton uitvoeren', 'Uitsluitend ronde gebouwen'],
      correctIndex: 0,
      explanation: 'Circulair bouwen richt zich op hergebruik: remontabel bouwen met herbruikbare, liefst bio-based materialen.',
    },
    {
      id: 'D.4.k5', toetstermCode: 'D.4.6', type: 'mc',
      prompt: 'Waar staat ESG voor in de vastgoedwereld?',
      options: ['Environmental, Social en Governance', 'Energie, Subsidie en Garantie', 'Extra Servicekosten Gebouw', 'Europese Standaard Gebouwen'],
      correctIndex: 0,
      explanation: 'ESG = Environmental, Social en Governance: criteria voor duurzaamheid en maatschappelijke impact van vastgoed.',
    },
  ],
}
